// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: etc/protos/system_data_for_client.proto

package com.s13g.winston.proto;

public final class ForClients {
  private ForClients() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SystemDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.s13g.winston.proto.SystemData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Whether the request for this data was successful. 
     * </pre>
     *
     * <code>optional bool success = 1;</code>
     */
    boolean getSuccess();

    /**
     * <pre>
     * All the I/Os that are known to the system. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
     */
    java.util.List<com.s13g.winston.proto.ForClients.SystemData.IoChannel> 
        getIoChannelList();
    /**
     * <pre>
     * All the I/Os that are known to the system. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
     */
    com.s13g.winston.proto.ForClients.SystemData.IoChannel getIoChannel(int index);
    /**
     * <pre>
     * All the I/Os that are known to the system. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
     */
    int getIoChannelCount();
    /**
     * <pre>
     * All the I/Os that are known to the system. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
     */
    java.util.List<? extends com.s13g.winston.proto.ForClients.SystemData.IoChannelOrBuilder> 
        getIoChannelOrBuilderList();
    /**
     * <pre>
     * All the I/Os that are known to the system. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
     */
    com.s13g.winston.proto.ForClients.SystemData.IoChannelOrBuilder getIoChannelOrBuilder(
        int index);
  }
  /**
   * <pre>
   * Contains whole system data loaded by a client. 
   * </pre>
   *
   * Protobuf type {@code com.s13g.winston.proto.SystemData}
   */
  public  static final class SystemData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.s13g.winston.proto.SystemData)
      SystemDataOrBuilder {
    // Use SystemData.newBuilder() to construct.
    private SystemData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SystemData() {
      success_ = false;
      ioChannel_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SystemData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                ioChannel_ = new java.util.ArrayList<com.s13g.winston.proto.ForClients.SystemData.IoChannel>();
                mutable_bitField0_ |= 0x00000002;
              }
              ioChannel_.add(
                  input.readMessage(com.s13g.winston.proto.ForClients.SystemData.IoChannel.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          ioChannel_ = java.util.Collections.unmodifiableList(ioChannel_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.s13g.winston.proto.ForClients.internal_static_com_s13g_winston_proto_SystemData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.s13g.winston.proto.ForClients.internal_static_com_s13g_winston_proto_SystemData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.s13g.winston.proto.ForClients.SystemData.class, com.s13g.winston.proto.ForClients.SystemData.Builder.class);
    }

    public interface IoChannelOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.s13g.winston.proto.SystemData.IoChannel)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * System-wide unique ID, e.g. '/pi-power-1/io/relay/0'. 
       * </pre>
       *
       * <code>optional string id = 1;</code>
       */
      java.lang.String getId();
      /**
       * <pre>
       * System-wide unique ID, e.g. '/pi-power-1/io/relay/0'. 
       * </pre>
       *
       * <code>optional string id = 1;</code>
       */
      com.google.protobuf.ByteString
          getIdBytes();

      /**
       * <pre>
       * The type of the channel, like 'temperature' etc. 
       * </pre>
       *
       * <code>optional string type = 2;</code>
       */
      java.lang.String getType();
      /**
       * <pre>
       * The type of the channel, like 'temperature' etc. 
       * </pre>
       *
       * <code>optional string type = 2;</code>
       */
      com.google.protobuf.ByteString
          getTypeBytes();

      /**
       * <pre>
       * Human readable name, to be used as a label. 
       * </pre>
       *
       * <code>optional string name = 3;</code>
       */
      java.lang.String getName();
      /**
       * <pre>
       * Human readable name, to be used as a label. 
       * </pre>
       *
       * <code>optional string name = 3;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * <pre>
     * Defines a single IoChannel. 
     * </pre>
     *
     * Protobuf type {@code com.s13g.winston.proto.SystemData.IoChannel}
     */
    public  static final class IoChannel extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.s13g.winston.proto.SystemData.IoChannel)
        IoChannelOrBuilder {
      // Use IoChannel.newBuilder() to construct.
      private IoChannel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private IoChannel() {
        id_ = "";
        type_ = "";
        name_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private IoChannel(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                id_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                type_ = s;
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.s13g.winston.proto.ForClients.internal_static_com_s13g_winston_proto_SystemData_IoChannel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.s13g.winston.proto.ForClients.internal_static_com_s13g_winston_proto_SystemData_IoChannel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.s13g.winston.proto.ForClients.SystemData.IoChannel.class, com.s13g.winston.proto.ForClients.SystemData.IoChannel.Builder.class);
      }

      public static final int ID_FIELD_NUMBER = 1;
      private volatile java.lang.Object id_;
      /**
       * <pre>
       * System-wide unique ID, e.g. '/pi-power-1/io/relay/0'. 
       * </pre>
       *
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * System-wide unique ID, e.g. '/pi-power-1/io/relay/0'. 
       * </pre>
       *
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private volatile java.lang.Object type_;
      /**
       * <pre>
       * The type of the channel, like 'temperature' etc. 
       * </pre>
       *
       * <code>optional string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * The type of the channel, like 'temperature' etc. 
       * </pre>
       *
       * <code>optional string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int NAME_FIELD_NUMBER = 3;
      private volatile java.lang.Object name_;
      /**
       * <pre>
       * Human readable name, to be used as a label. 
       * </pre>
       *
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * Human readable name, to be used as a label. 
       * </pre>
       *
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getIdBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
        }
        if (!getTypeBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
        }
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getIdBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
        }
        if (!getTypeBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
        }
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.s13g.winston.proto.ForClients.SystemData.IoChannel)) {
          return super.equals(obj);
        }
        com.s13g.winston.proto.ForClients.SystemData.IoChannel other = (com.s13g.winston.proto.ForClients.SystemData.IoChannel) obj;

        boolean result = true;
        result = result && getId()
            .equals(other.getId());
        result = result && getType()
            .equals(other.getType());
        result = result && getName()
            .equals(other.getName());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.s13g.winston.proto.ForClients.SystemData.IoChannel parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.s13g.winston.proto.ForClients.SystemData.IoChannel parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.s13g.winston.proto.ForClients.SystemData.IoChannel parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.s13g.winston.proto.ForClients.SystemData.IoChannel parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.s13g.winston.proto.ForClients.SystemData.IoChannel parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.s13g.winston.proto.ForClients.SystemData.IoChannel parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.s13g.winston.proto.ForClients.SystemData.IoChannel parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.s13g.winston.proto.ForClients.SystemData.IoChannel parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.s13g.winston.proto.ForClients.SystemData.IoChannel parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.s13g.winston.proto.ForClients.SystemData.IoChannel parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.s13g.winston.proto.ForClients.SystemData.IoChannel prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * Defines a single IoChannel. 
       * </pre>
       *
       * Protobuf type {@code com.s13g.winston.proto.SystemData.IoChannel}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.s13g.winston.proto.SystemData.IoChannel)
          com.s13g.winston.proto.ForClients.SystemData.IoChannelOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.s13g.winston.proto.ForClients.internal_static_com_s13g_winston_proto_SystemData_IoChannel_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.s13g.winston.proto.ForClients.internal_static_com_s13g_winston_proto_SystemData_IoChannel_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.s13g.winston.proto.ForClients.SystemData.IoChannel.class, com.s13g.winston.proto.ForClients.SystemData.IoChannel.Builder.class);
        }

        // Construct using com.s13g.winston.proto.ForClients.SystemData.IoChannel.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          id_ = "";

          type_ = "";

          name_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.s13g.winston.proto.ForClients.internal_static_com_s13g_winston_proto_SystemData_IoChannel_descriptor;
        }

        public com.s13g.winston.proto.ForClients.SystemData.IoChannel getDefaultInstanceForType() {
          return com.s13g.winston.proto.ForClients.SystemData.IoChannel.getDefaultInstance();
        }

        public com.s13g.winston.proto.ForClients.SystemData.IoChannel build() {
          com.s13g.winston.proto.ForClients.SystemData.IoChannel result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.s13g.winston.proto.ForClients.SystemData.IoChannel buildPartial() {
          com.s13g.winston.proto.ForClients.SystemData.IoChannel result = new com.s13g.winston.proto.ForClients.SystemData.IoChannel(this);
          result.id_ = id_;
          result.type_ = type_;
          result.name_ = name_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.s13g.winston.proto.ForClients.SystemData.IoChannel) {
            return mergeFrom((com.s13g.winston.proto.ForClients.SystemData.IoChannel)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.s13g.winston.proto.ForClients.SystemData.IoChannel other) {
          if (other == com.s13g.winston.proto.ForClients.SystemData.IoChannel.getDefaultInstance()) return this;
          if (!other.getId().isEmpty()) {
            id_ = other.id_;
            onChanged();
          }
          if (!other.getType().isEmpty()) {
            type_ = other.type_;
            onChanged();
          }
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.s13g.winston.proto.ForClients.SystemData.IoChannel parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.s13g.winston.proto.ForClients.SystemData.IoChannel) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object id_ = "";
        /**
         * <pre>
         * System-wide unique ID, e.g. '/pi-power-1/io/relay/0'. 
         * </pre>
         *
         * <code>optional string id = 1;</code>
         */
        public java.lang.String getId() {
          java.lang.Object ref = id_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            id_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * System-wide unique ID, e.g. '/pi-power-1/io/relay/0'. 
         * </pre>
         *
         * <code>optional string id = 1;</code>
         */
        public com.google.protobuf.ByteString
            getIdBytes() {
          java.lang.Object ref = id_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            id_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * System-wide unique ID, e.g. '/pi-power-1/io/relay/0'. 
         * </pre>
         *
         * <code>optional string id = 1;</code>
         */
        public Builder setId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * System-wide unique ID, e.g. '/pi-power-1/io/relay/0'. 
         * </pre>
         *
         * <code>optional string id = 1;</code>
         */
        public Builder clearId() {
          
          id_ = getDefaultInstance().getId();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * System-wide unique ID, e.g. '/pi-power-1/io/relay/0'. 
         * </pre>
         *
         * <code>optional string id = 1;</code>
         */
        public Builder setIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          id_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object type_ = "";
        /**
         * <pre>
         * The type of the channel, like 'temperature' etc. 
         * </pre>
         *
         * <code>optional string type = 2;</code>
         */
        public java.lang.String getType() {
          java.lang.Object ref = type_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            type_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * The type of the channel, like 'temperature' etc. 
         * </pre>
         *
         * <code>optional string type = 2;</code>
         */
        public com.google.protobuf.ByteString
            getTypeBytes() {
          java.lang.Object ref = type_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            type_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * The type of the channel, like 'temperature' etc. 
         * </pre>
         *
         * <code>optional string type = 2;</code>
         */
        public Builder setType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * The type of the channel, like 'temperature' etc. 
         * </pre>
         *
         * <code>optional string type = 2;</code>
         */
        public Builder clearType() {
          
          type_ = getDefaultInstance().getType();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * The type of the channel, like 'temperature' etc. 
         * </pre>
         *
         * <code>optional string type = 2;</code>
         */
        public Builder setTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          type_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <pre>
         * Human readable name, to be used as a label. 
         * </pre>
         *
         * <code>optional string name = 3;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * Human readable name, to be used as a label. 
         * </pre>
         *
         * <code>optional string name = 3;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * Human readable name, to be used as a label. 
         * </pre>
         *
         * <code>optional string name = 3;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Human readable name, to be used as a label. 
         * </pre>
         *
         * <code>optional string name = 3;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Human readable name, to be used as a label. 
         * </pre>
         *
         * <code>optional string name = 3;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:com.s13g.winston.proto.SystemData.IoChannel)
      }

      // @@protoc_insertion_point(class_scope:com.s13g.winston.proto.SystemData.IoChannel)
      private static final com.s13g.winston.proto.ForClients.SystemData.IoChannel DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.s13g.winston.proto.ForClients.SystemData.IoChannel();
      }

      public static com.s13g.winston.proto.ForClients.SystemData.IoChannel getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<IoChannel>
          PARSER = new com.google.protobuf.AbstractParser<IoChannel>() {
        public IoChannel parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new IoChannel(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<IoChannel> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<IoChannel> getParserForType() {
        return PARSER;
      }

      public com.s13g.winston.proto.ForClients.SystemData.IoChannel getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <pre>
     * Whether the request for this data was successful. 
     * </pre>
     *
     * <code>optional bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int IO_CHANNEL_FIELD_NUMBER = 2;
    private java.util.List<com.s13g.winston.proto.ForClients.SystemData.IoChannel> ioChannel_;
    /**
     * <pre>
     * All the I/Os that are known to the system. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
     */
    public java.util.List<com.s13g.winston.proto.ForClients.SystemData.IoChannel> getIoChannelList() {
      return ioChannel_;
    }
    /**
     * <pre>
     * All the I/Os that are known to the system. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
     */
    public java.util.List<? extends com.s13g.winston.proto.ForClients.SystemData.IoChannelOrBuilder> 
        getIoChannelOrBuilderList() {
      return ioChannel_;
    }
    /**
     * <pre>
     * All the I/Os that are known to the system. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
     */
    public int getIoChannelCount() {
      return ioChannel_.size();
    }
    /**
     * <pre>
     * All the I/Os that are known to the system. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
     */
    public com.s13g.winston.proto.ForClients.SystemData.IoChannel getIoChannel(int index) {
      return ioChannel_.get(index);
    }
    /**
     * <pre>
     * All the I/Os that are known to the system. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
     */
    public com.s13g.winston.proto.ForClients.SystemData.IoChannelOrBuilder getIoChannelOrBuilder(
        int index) {
      return ioChannel_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      for (int i = 0; i < ioChannel_.size(); i++) {
        output.writeMessage(2, ioChannel_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      for (int i = 0; i < ioChannel_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, ioChannel_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.s13g.winston.proto.ForClients.SystemData)) {
        return super.equals(obj);
      }
      com.s13g.winston.proto.ForClients.SystemData other = (com.s13g.winston.proto.ForClients.SystemData) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && getIoChannelList()
          .equals(other.getIoChannelList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      if (getIoChannelCount() > 0) {
        hash = (37 * hash) + IO_CHANNEL_FIELD_NUMBER;
        hash = (53 * hash) + getIoChannelList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.s13g.winston.proto.ForClients.SystemData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.s13g.winston.proto.ForClients.SystemData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.s13g.winston.proto.ForClients.SystemData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.s13g.winston.proto.ForClients.SystemData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.s13g.winston.proto.ForClients.SystemData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.s13g.winston.proto.ForClients.SystemData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.s13g.winston.proto.ForClients.SystemData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.s13g.winston.proto.ForClients.SystemData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.s13g.winston.proto.ForClients.SystemData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.s13g.winston.proto.ForClients.SystemData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.s13g.winston.proto.ForClients.SystemData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Contains whole system data loaded by a client. 
     * </pre>
     *
     * Protobuf type {@code com.s13g.winston.proto.SystemData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.s13g.winston.proto.SystemData)
        com.s13g.winston.proto.ForClients.SystemDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.s13g.winston.proto.ForClients.internal_static_com_s13g_winston_proto_SystemData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.s13g.winston.proto.ForClients.internal_static_com_s13g_winston_proto_SystemData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.s13g.winston.proto.ForClients.SystemData.class, com.s13g.winston.proto.ForClients.SystemData.Builder.class);
      }

      // Construct using com.s13g.winston.proto.ForClients.SystemData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getIoChannelFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        success_ = false;

        if (ioChannelBuilder_ == null) {
          ioChannel_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ioChannelBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.s13g.winston.proto.ForClients.internal_static_com_s13g_winston_proto_SystemData_descriptor;
      }

      public com.s13g.winston.proto.ForClients.SystemData getDefaultInstanceForType() {
        return com.s13g.winston.proto.ForClients.SystemData.getDefaultInstance();
      }

      public com.s13g.winston.proto.ForClients.SystemData build() {
        com.s13g.winston.proto.ForClients.SystemData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.s13g.winston.proto.ForClients.SystemData buildPartial() {
        com.s13g.winston.proto.ForClients.SystemData result = new com.s13g.winston.proto.ForClients.SystemData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.success_ = success_;
        if (ioChannelBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            ioChannel_ = java.util.Collections.unmodifiableList(ioChannel_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.ioChannel_ = ioChannel_;
        } else {
          result.ioChannel_ = ioChannelBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.s13g.winston.proto.ForClients.SystemData) {
          return mergeFrom((com.s13g.winston.proto.ForClients.SystemData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.s13g.winston.proto.ForClients.SystemData other) {
        if (other == com.s13g.winston.proto.ForClients.SystemData.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (ioChannelBuilder_ == null) {
          if (!other.ioChannel_.isEmpty()) {
            if (ioChannel_.isEmpty()) {
              ioChannel_ = other.ioChannel_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureIoChannelIsMutable();
              ioChannel_.addAll(other.ioChannel_);
            }
            onChanged();
          }
        } else {
          if (!other.ioChannel_.isEmpty()) {
            if (ioChannelBuilder_.isEmpty()) {
              ioChannelBuilder_.dispose();
              ioChannelBuilder_ = null;
              ioChannel_ = other.ioChannel_;
              bitField0_ = (bitField0_ & ~0x00000002);
              ioChannelBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getIoChannelFieldBuilder() : null;
            } else {
              ioChannelBuilder_.addAllMessages(other.ioChannel_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.s13g.winston.proto.ForClients.SystemData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.s13g.winston.proto.ForClients.SystemData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <pre>
       * Whether the request for this data was successful. 
       * </pre>
       *
       * <code>optional bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <pre>
       * Whether the request for this data was successful. 
       * </pre>
       *
       * <code>optional bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether the request for this data was successful. 
       * </pre>
       *
       * <code>optional bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private java.util.List<com.s13g.winston.proto.ForClients.SystemData.IoChannel> ioChannel_ =
        java.util.Collections.emptyList();
      private void ensureIoChannelIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          ioChannel_ = new java.util.ArrayList<com.s13g.winston.proto.ForClients.SystemData.IoChannel>(ioChannel_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.s13g.winston.proto.ForClients.SystemData.IoChannel, com.s13g.winston.proto.ForClients.SystemData.IoChannel.Builder, com.s13g.winston.proto.ForClients.SystemData.IoChannelOrBuilder> ioChannelBuilder_;

      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public java.util.List<com.s13g.winston.proto.ForClients.SystemData.IoChannel> getIoChannelList() {
        if (ioChannelBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ioChannel_);
        } else {
          return ioChannelBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public int getIoChannelCount() {
        if (ioChannelBuilder_ == null) {
          return ioChannel_.size();
        } else {
          return ioChannelBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public com.s13g.winston.proto.ForClients.SystemData.IoChannel getIoChannel(int index) {
        if (ioChannelBuilder_ == null) {
          return ioChannel_.get(index);
        } else {
          return ioChannelBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public Builder setIoChannel(
          int index, com.s13g.winston.proto.ForClients.SystemData.IoChannel value) {
        if (ioChannelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIoChannelIsMutable();
          ioChannel_.set(index, value);
          onChanged();
        } else {
          ioChannelBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public Builder setIoChannel(
          int index, com.s13g.winston.proto.ForClients.SystemData.IoChannel.Builder builderForValue) {
        if (ioChannelBuilder_ == null) {
          ensureIoChannelIsMutable();
          ioChannel_.set(index, builderForValue.build());
          onChanged();
        } else {
          ioChannelBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public Builder addIoChannel(com.s13g.winston.proto.ForClients.SystemData.IoChannel value) {
        if (ioChannelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIoChannelIsMutable();
          ioChannel_.add(value);
          onChanged();
        } else {
          ioChannelBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public Builder addIoChannel(
          int index, com.s13g.winston.proto.ForClients.SystemData.IoChannel value) {
        if (ioChannelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIoChannelIsMutable();
          ioChannel_.add(index, value);
          onChanged();
        } else {
          ioChannelBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public Builder addIoChannel(
          com.s13g.winston.proto.ForClients.SystemData.IoChannel.Builder builderForValue) {
        if (ioChannelBuilder_ == null) {
          ensureIoChannelIsMutable();
          ioChannel_.add(builderForValue.build());
          onChanged();
        } else {
          ioChannelBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public Builder addIoChannel(
          int index, com.s13g.winston.proto.ForClients.SystemData.IoChannel.Builder builderForValue) {
        if (ioChannelBuilder_ == null) {
          ensureIoChannelIsMutable();
          ioChannel_.add(index, builderForValue.build());
          onChanged();
        } else {
          ioChannelBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public Builder addAllIoChannel(
          java.lang.Iterable<? extends com.s13g.winston.proto.ForClients.SystemData.IoChannel> values) {
        if (ioChannelBuilder_ == null) {
          ensureIoChannelIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ioChannel_);
          onChanged();
        } else {
          ioChannelBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public Builder clearIoChannel() {
        if (ioChannelBuilder_ == null) {
          ioChannel_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          ioChannelBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public Builder removeIoChannel(int index) {
        if (ioChannelBuilder_ == null) {
          ensureIoChannelIsMutable();
          ioChannel_.remove(index);
          onChanged();
        } else {
          ioChannelBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public com.s13g.winston.proto.ForClients.SystemData.IoChannel.Builder getIoChannelBuilder(
          int index) {
        return getIoChannelFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public com.s13g.winston.proto.ForClients.SystemData.IoChannelOrBuilder getIoChannelOrBuilder(
          int index) {
        if (ioChannelBuilder_ == null) {
          return ioChannel_.get(index);  } else {
          return ioChannelBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public java.util.List<? extends com.s13g.winston.proto.ForClients.SystemData.IoChannelOrBuilder> 
           getIoChannelOrBuilderList() {
        if (ioChannelBuilder_ != null) {
          return ioChannelBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ioChannel_);
        }
      }
      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public com.s13g.winston.proto.ForClients.SystemData.IoChannel.Builder addIoChannelBuilder() {
        return getIoChannelFieldBuilder().addBuilder(
            com.s13g.winston.proto.ForClients.SystemData.IoChannel.getDefaultInstance());
      }
      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public com.s13g.winston.proto.ForClients.SystemData.IoChannel.Builder addIoChannelBuilder(
          int index) {
        return getIoChannelFieldBuilder().addBuilder(
            index, com.s13g.winston.proto.ForClients.SystemData.IoChannel.getDefaultInstance());
      }
      /**
       * <pre>
       * All the I/Os that are known to the system. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;</code>
       */
      public java.util.List<com.s13g.winston.proto.ForClients.SystemData.IoChannel.Builder> 
           getIoChannelBuilderList() {
        return getIoChannelFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.s13g.winston.proto.ForClients.SystemData.IoChannel, com.s13g.winston.proto.ForClients.SystemData.IoChannel.Builder, com.s13g.winston.proto.ForClients.SystemData.IoChannelOrBuilder> 
          getIoChannelFieldBuilder() {
        if (ioChannelBuilder_ == null) {
          ioChannelBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.s13g.winston.proto.ForClients.SystemData.IoChannel, com.s13g.winston.proto.ForClients.SystemData.IoChannel.Builder, com.s13g.winston.proto.ForClients.SystemData.IoChannelOrBuilder>(
                  ioChannel_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          ioChannel_ = null;
        }
        return ioChannelBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.s13g.winston.proto.SystemData)
    }

    // @@protoc_insertion_point(class_scope:com.s13g.winston.proto.SystemData)
    private static final com.s13g.winston.proto.ForClients.SystemData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.s13g.winston.proto.ForClients.SystemData();
    }

    public static com.s13g.winston.proto.ForClients.SystemData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SystemData>
        PARSER = new com.google.protobuf.AbstractParser<SystemData>() {
      public SystemData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SystemData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SystemData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SystemData> getParserForType() {
      return PARSER;
    }

    public com.s13g.winston.proto.ForClients.SystemData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_s13g_winston_proto_SystemData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_s13g_winston_proto_SystemData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_s13g_winston_proto_SystemData_IoChannel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_s13g_winston_proto_SystemData_IoChannel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'etc/protos/system_data_for_client.prot" +
      "o\022\026com.s13g.winston.proto\"\224\001\n\nSystemData" +
      "\022\017\n\007success\030\001 \001(\010\022@\n\nio_channel\030\002 \003(\0132,." +
      "com.s13g.winston.proto.SystemData.IoChan" +
      "nel\0323\n\tIoChannel\022\n\n\002id\030\001 \001(\t\022\014\n\004type\030\002 \001" +
      "(\t\022\014\n\004name\030\003 \001(\tB$\n\026com.s13g.winston.pro" +
      "toB\nForClientsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_s13g_winston_proto_SystemData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_s13g_winston_proto_SystemData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_s13g_winston_proto_SystemData_descriptor,
        new java.lang.String[] { "Success", "IoChannel", });
    internal_static_com_s13g_winston_proto_SystemData_IoChannel_descriptor =
      internal_static_com_s13g_winston_proto_SystemData_descriptor.getNestedTypes().get(0);
    internal_static_com_s13g_winston_proto_SystemData_IoChannel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_s13g_winston_proto_SystemData_IoChannel_descriptor,
        new java.lang.String[] { "Id", "Type", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
