// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.s13g.winston.proto.nano;

@SuppressWarnings("hiding")
public interface ForClients {

  public static final class SystemData extends
      com.google.protobuf.nano.MessageNano {

    public static final class IoChannel extends
        com.google.protobuf.nano.MessageNano {

      private static volatile IoChannel[] _emptyArray;
      public static IoChannel[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new IoChannel[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional string id = 1;
      public java.lang.String id;

      // optional string type = 2;
      public java.lang.String type;

      // optional string name = 3;
      public java.lang.String name;

      public IoChannel() {
        clear();
      }

      public IoChannel clear() {
        id = "";
        type = "";
        name = "";
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!this.id.equals("")) {
          output.writeString(1, this.id);
        }
        if (!this.type.equals("")) {
          output.writeString(2, this.type);
        }
        if (!this.name.equals("")) {
          output.writeString(3, this.name);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!this.id.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, this.id);
        }
        if (!this.type.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(2, this.type);
        }
        if (!this.name.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(3, this.name);
        }
        return size;
      }

      @Override
      public IoChannel mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.id = input.readString();
              break;
            }
            case 18: {
              this.type = input.readString();
              break;
            }
            case 26: {
              this.name = input.readString();
              break;
            }
          }
        }
      }

      public static IoChannel parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new IoChannel(), data);
      }

      public static IoChannel parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new IoChannel().mergeFrom(input);
      }
    }

    private static volatile SystemData[] _emptyArray;
    public static SystemData[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SystemData[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bool success = 1;
    public boolean success;

    // repeated .com.s13g.winston.proto.SystemData.IoChannel io_channel = 2;
    public com.s13g.winston.proto.nano.ForClients.SystemData.IoChannel[] ioChannel;

    public SystemData() {
      clear();
    }

    public SystemData clear() {
      success = false;
      ioChannel = com.s13g.winston.proto.nano.ForClients.SystemData.IoChannel.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.success != false) {
        output.writeBool(1, this.success);
      }
      if (this.ioChannel != null && this.ioChannel.length > 0) {
        for (int i = 0; i < this.ioChannel.length; i++) {
          com.s13g.winston.proto.nano.ForClients.SystemData.IoChannel element = this.ioChannel[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.success != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, this.success);
      }
      if (this.ioChannel != null && this.ioChannel.length > 0) {
        for (int i = 0; i < this.ioChannel.length; i++) {
          com.s13g.winston.proto.nano.ForClients.SystemData.IoChannel element = this.ioChannel[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      return size;
    }

    @Override
    public SystemData mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.success = input.readBool();
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.ioChannel == null ? 0 : this.ioChannel.length;
            com.s13g.winston.proto.nano.ForClients.SystemData.IoChannel[] newArray =
                new com.s13g.winston.proto.nano.ForClients.SystemData.IoChannel[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.ioChannel, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.s13g.winston.proto.nano.ForClients.SystemData.IoChannel();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.s13g.winston.proto.nano.ForClients.SystemData.IoChannel();
            input.readMessage(newArray[i]);
            this.ioChannel = newArray;
            break;
          }
        }
      }
    }

    public static SystemData parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SystemData(), data);
    }

    public static SystemData parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SystemData().mergeFrom(input);
    }
  }
}
