// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: etc/protos/master_config.proto

package com.s13g.winston.master.proto;

public final class MasterProtos {
  private MasterProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.s13g.winston.master.proto.Config)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 daemon_port = 1;</code>
     *
     * <pre>
     * The port to start the maste daemon on. 
     * </pre>
     */
    boolean hasDaemonPort();
    /**
     * <code>required int32 daemon_port = 1;</code>
     *
     * <pre>
     * The port to start the maste daemon on. 
     * </pre>
     */
    int getDaemonPort();

    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     *
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     */
    java.util.List<com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping> 
        getNodeMappingList();
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     *
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     */
    com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping getNodeMapping(int index);
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     *
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     */
    int getNodeMappingCount();
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     *
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     */
    java.util.List<? extends com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder> 
        getNodeMappingOrBuilderList();
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     *
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     */
    com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder getNodeMappingOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.s13g.winston.master.proto.Config}
   *
   * <pre>
   * Configuration for the master daemon. 
   * </pre>
   */
  public static final class Config extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.s13g.winston.master.proto.Config)
      ConfigOrBuilder {
    // Use Config.newBuilder() to construct.
    private Config(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Config(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Config defaultInstance;
    public static Config getDefaultInstance() {
      return defaultInstance;
    }

    public Config getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Config(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              daemonPort_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                nodeMapping_ = new java.util.ArrayList<com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping>();
                mutable_bitField0_ |= 0x00000002;
              }
              nodeMapping_.add(input.readMessage(com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          nodeMapping_ = java.util.Collections.unmodifiableList(nodeMapping_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.s13g.winston.master.proto.MasterProtos.Config.class, com.s13g.winston.master.proto.MasterProtos.Config.Builder.class);
    }

    public static com.google.protobuf.Parser<Config> PARSER =
        new com.google.protobuf.AbstractParser<Config>() {
      public Config parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Config(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Config> getParserForType() {
      return PARSER;
    }

    public interface NodeMappingOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.s13g.winston.master.proto.Config.NodeMapping)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * Name of the node, like "pi-garage". 
       * </pre>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * Name of the node, like "pi-garage". 
       * </pre>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * Name of the node, like "pi-garage". 
       * </pre>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>required string address = 2;</code>
       *
       * <pre>
       * The IP address of the node. 
       * </pre>
       */
      boolean hasAddress();
      /**
       * <code>required string address = 2;</code>
       *
       * <pre>
       * The IP address of the node. 
       * </pre>
       */
      java.lang.String getAddress();
      /**
       * <code>required string address = 2;</code>
       *
       * <pre>
       * The IP address of the node. 
       * </pre>
       */
      com.google.protobuf.ByteString
          getAddressBytes();

      /**
       * <code>required int32 port = 3;</code>
       *
       * <pre>
       * The port to access the node daemon, typically 1984. 
       * </pre>
       */
      boolean hasPort();
      /**
       * <code>required int32 port = 3;</code>
       *
       * <pre>
       * The port to access the node daemon, typically 1984. 
       * </pre>
       */
      int getPort();

      /**
       * <code>required bool use_ssl = 4;</code>
       *
       * <pre>
       * Whether the node daemon should accessed through https. 
       * </pre>
       */
      boolean hasUseSsl();
      /**
       * <code>required bool use_ssl = 4;</code>
       *
       * <pre>
       * Whether the node daemon should accessed through https. 
       * </pre>
       */
      boolean getUseSsl();
    }
    /**
     * Protobuf type {@code com.s13g.winston.master.proto.Config.NodeMapping}
     *
     * <pre>
     * Mapping from tag to node. 
     * </pre>
     */
    public static final class NodeMapping extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:com.s13g.winston.master.proto.Config.NodeMapping)
        NodeMappingOrBuilder {
      // Use NodeMapping.newBuilder() to construct.
      private NodeMapping(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private NodeMapping(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final NodeMapping defaultInstance;
      public static NodeMapping getDefaultInstance() {
        return defaultInstance;
      }

      public NodeMapping getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private NodeMapping(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                name_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                address_ = bs;
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                port_ = input.readInt32();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                useSsl_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_NodeMapping_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_NodeMapping_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.class, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder.class);
      }

      public static com.google.protobuf.Parser<NodeMapping> PARSER =
          new com.google.protobuf.AbstractParser<NodeMapping>() {
        public NodeMapping parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new NodeMapping(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<NodeMapping> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * Name of the node, like "pi-garage". 
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * Name of the node, like "pi-garage". 
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * Name of the node, like "pi-garage". 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ADDRESS_FIELD_NUMBER = 2;
      private java.lang.Object address_;
      /**
       * <code>required string address = 2;</code>
       *
       * <pre>
       * The IP address of the node. 
       * </pre>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string address = 2;</code>
       *
       * <pre>
       * The IP address of the node. 
       * </pre>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string address = 2;</code>
       *
       * <pre>
       * The IP address of the node. 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PORT_FIELD_NUMBER = 3;
      private int port_;
      /**
       * <code>required int32 port = 3;</code>
       *
       * <pre>
       * The port to access the node daemon, typically 1984. 
       * </pre>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 port = 3;</code>
       *
       * <pre>
       * The port to access the node daemon, typically 1984. 
       * </pre>
       */
      public int getPort() {
        return port_;
      }

      public static final int USE_SSL_FIELD_NUMBER = 4;
      private boolean useSsl_;
      /**
       * <code>required bool use_ssl = 4;</code>
       *
       * <pre>
       * Whether the node daemon should accessed through https. 
       * </pre>
       */
      public boolean hasUseSsl() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bool use_ssl = 4;</code>
       *
       * <pre>
       * Whether the node daemon should accessed through https. 
       * </pre>
       */
      public boolean getUseSsl() {
        return useSsl_;
      }

      private void initFields() {
        name_ = "";
        address_ = "";
        port_ = 0;
        useSsl_ = false;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasAddress()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPort()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasUseSsl()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getAddressBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, port_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBool(4, useSsl_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getAddressBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, port_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(4, useSsl_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.s13g.winston.master.proto.Config.NodeMapping}
       *
       * <pre>
       * Mapping from tag to node. 
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.s13g.winston.master.proto.Config.NodeMapping)
          com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_NodeMapping_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_NodeMapping_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.class, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder.class);
        }

        // Construct using com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          address_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          port_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          useSsl_ = false;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_NodeMapping_descriptor;
        }

        public com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping getDefaultInstanceForType() {
          return com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.getDefaultInstance();
        }

        public com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping build() {
          com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping buildPartial() {
          com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping result = new com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.address_ = address_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.port_ = port_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.useSsl_ = useSsl_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping) {
            return mergeFrom((com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping other) {
          if (other == com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasAddress()) {
            bitField0_ |= 0x00000002;
            address_ = other.address_;
            onChanged();
          }
          if (other.hasPort()) {
            setPort(other.getPort());
          }
          if (other.hasUseSsl()) {
            setUseSsl(other.getUseSsl());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          if (!hasAddress()) {
            
            return false;
          }
          if (!hasPort()) {
            
            return false;
          }
          if (!hasUseSsl()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         *
         * <pre>
         * Name of the node, like "pi-garage". 
         * </pre>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         *
         * <pre>
         * Name of the node, like "pi-garage". 
         * </pre>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              name_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         *
         * <pre>
         * Name of the node, like "pi-garage". 
         * </pre>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         *
         * <pre>
         * Name of the node, like "pi-garage". 
         * </pre>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         *
         * <pre>
         * Name of the node, like "pi-garage". 
         * </pre>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         *
         * <pre>
         * Name of the node, like "pi-garage". 
         * </pre>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object address_ = "";
        /**
         * <code>required string address = 2;</code>
         *
         * <pre>
         * The IP address of the node. 
         * </pre>
         */
        public boolean hasAddress() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string address = 2;</code>
         *
         * <pre>
         * The IP address of the node. 
         * </pre>
         */
        public java.lang.String getAddress() {
          java.lang.Object ref = address_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              address_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string address = 2;</code>
         *
         * <pre>
         * The IP address of the node. 
         * </pre>
         */
        public com.google.protobuf.ByteString
            getAddressBytes() {
          java.lang.Object ref = address_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            address_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string address = 2;</code>
         *
         * <pre>
         * The IP address of the node. 
         * </pre>
         */
        public Builder setAddress(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          address_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string address = 2;</code>
         *
         * <pre>
         * The IP address of the node. 
         * </pre>
         */
        public Builder clearAddress() {
          bitField0_ = (bitField0_ & ~0x00000002);
          address_ = getDefaultInstance().getAddress();
          onChanged();
          return this;
        }
        /**
         * <code>required string address = 2;</code>
         *
         * <pre>
         * The IP address of the node. 
         * </pre>
         */
        public Builder setAddressBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          address_ = value;
          onChanged();
          return this;
        }

        private int port_ ;
        /**
         * <code>required int32 port = 3;</code>
         *
         * <pre>
         * The port to access the node daemon, typically 1984. 
         * </pre>
         */
        public boolean hasPort() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required int32 port = 3;</code>
         *
         * <pre>
         * The port to access the node daemon, typically 1984. 
         * </pre>
         */
        public int getPort() {
          return port_;
        }
        /**
         * <code>required int32 port = 3;</code>
         *
         * <pre>
         * The port to access the node daemon, typically 1984. 
         * </pre>
         */
        public Builder setPort(int value) {
          bitField0_ |= 0x00000004;
          port_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 port = 3;</code>
         *
         * <pre>
         * The port to access the node daemon, typically 1984. 
         * </pre>
         */
        public Builder clearPort() {
          bitField0_ = (bitField0_ & ~0x00000004);
          port_ = 0;
          onChanged();
          return this;
        }

        private boolean useSsl_ ;
        /**
         * <code>required bool use_ssl = 4;</code>
         *
         * <pre>
         * Whether the node daemon should accessed through https. 
         * </pre>
         */
        public boolean hasUseSsl() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required bool use_ssl = 4;</code>
         *
         * <pre>
         * Whether the node daemon should accessed through https. 
         * </pre>
         */
        public boolean getUseSsl() {
          return useSsl_;
        }
        /**
         * <code>required bool use_ssl = 4;</code>
         *
         * <pre>
         * Whether the node daemon should accessed through https. 
         * </pre>
         */
        public Builder setUseSsl(boolean value) {
          bitField0_ |= 0x00000008;
          useSsl_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bool use_ssl = 4;</code>
         *
         * <pre>
         * Whether the node daemon should accessed through https. 
         * </pre>
         */
        public Builder clearUseSsl() {
          bitField0_ = (bitField0_ & ~0x00000008);
          useSsl_ = false;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.s13g.winston.master.proto.Config.NodeMapping)
      }

      static {
        defaultInstance = new NodeMapping(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.s13g.winston.master.proto.Config.NodeMapping)
    }

    private int bitField0_;
    public static final int DAEMON_PORT_FIELD_NUMBER = 1;
    private int daemonPort_;
    /**
     * <code>required int32 daemon_port = 1;</code>
     *
     * <pre>
     * The port to start the maste daemon on. 
     * </pre>
     */
    public boolean hasDaemonPort() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 daemon_port = 1;</code>
     *
     * <pre>
     * The port to start the maste daemon on. 
     * </pre>
     */
    public int getDaemonPort() {
      return daemonPort_;
    }

    public static final int NODE_MAPPING_FIELD_NUMBER = 2;
    private java.util.List<com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping> nodeMapping_;
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     *
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     */
    public java.util.List<com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping> getNodeMappingList() {
      return nodeMapping_;
    }
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     *
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     */
    public java.util.List<? extends com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder> 
        getNodeMappingOrBuilderList() {
      return nodeMapping_;
    }
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     *
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     */
    public int getNodeMappingCount() {
      return nodeMapping_.size();
    }
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     *
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     */
    public com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping getNodeMapping(int index) {
      return nodeMapping_.get(index);
    }
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     *
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     */
    public com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder getNodeMappingOrBuilder(
        int index) {
      return nodeMapping_.get(index);
    }

    private void initFields() {
      daemonPort_ = 0;
      nodeMapping_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDaemonPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getNodeMappingCount(); i++) {
        if (!getNodeMapping(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, daemonPort_);
      }
      for (int i = 0; i < nodeMapping_.size(); i++) {
        output.writeMessage(2, nodeMapping_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, daemonPort_);
      }
      for (int i = 0; i < nodeMapping_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, nodeMapping_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.s13g.winston.master.proto.MasterProtos.Config parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.s13g.winston.master.proto.MasterProtos.Config prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.s13g.winston.master.proto.Config}
     *
     * <pre>
     * Configuration for the master daemon. 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.s13g.winston.master.proto.Config)
        com.s13g.winston.master.proto.MasterProtos.ConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.s13g.winston.master.proto.MasterProtos.Config.class, com.s13g.winston.master.proto.MasterProtos.Config.Builder.class);
      }

      // Construct using com.s13g.winston.master.proto.MasterProtos.Config.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNodeMappingFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        daemonPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (nodeMappingBuilder_ == null) {
          nodeMapping_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          nodeMappingBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_descriptor;
      }

      public com.s13g.winston.master.proto.MasterProtos.Config getDefaultInstanceForType() {
        return com.s13g.winston.master.proto.MasterProtos.Config.getDefaultInstance();
      }

      public com.s13g.winston.master.proto.MasterProtos.Config build() {
        com.s13g.winston.master.proto.MasterProtos.Config result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.s13g.winston.master.proto.MasterProtos.Config buildPartial() {
        com.s13g.winston.master.proto.MasterProtos.Config result = new com.s13g.winston.master.proto.MasterProtos.Config(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.daemonPort_ = daemonPort_;
        if (nodeMappingBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            nodeMapping_ = java.util.Collections.unmodifiableList(nodeMapping_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.nodeMapping_ = nodeMapping_;
        } else {
          result.nodeMapping_ = nodeMappingBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.s13g.winston.master.proto.MasterProtos.Config) {
          return mergeFrom((com.s13g.winston.master.proto.MasterProtos.Config)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.s13g.winston.master.proto.MasterProtos.Config other) {
        if (other == com.s13g.winston.master.proto.MasterProtos.Config.getDefaultInstance()) return this;
        if (other.hasDaemonPort()) {
          setDaemonPort(other.getDaemonPort());
        }
        if (nodeMappingBuilder_ == null) {
          if (!other.nodeMapping_.isEmpty()) {
            if (nodeMapping_.isEmpty()) {
              nodeMapping_ = other.nodeMapping_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureNodeMappingIsMutable();
              nodeMapping_.addAll(other.nodeMapping_);
            }
            onChanged();
          }
        } else {
          if (!other.nodeMapping_.isEmpty()) {
            if (nodeMappingBuilder_.isEmpty()) {
              nodeMappingBuilder_.dispose();
              nodeMappingBuilder_ = null;
              nodeMapping_ = other.nodeMapping_;
              bitField0_ = (bitField0_ & ~0x00000002);
              nodeMappingBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNodeMappingFieldBuilder() : null;
            } else {
              nodeMappingBuilder_.addAllMessages(other.nodeMapping_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDaemonPort()) {
          
          return false;
        }
        for (int i = 0; i < getNodeMappingCount(); i++) {
          if (!getNodeMapping(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.s13g.winston.master.proto.MasterProtos.Config parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.s13g.winston.master.proto.MasterProtos.Config) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int daemonPort_ ;
      /**
       * <code>required int32 daemon_port = 1;</code>
       *
       * <pre>
       * The port to start the maste daemon on. 
       * </pre>
       */
      public boolean hasDaemonPort() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 daemon_port = 1;</code>
       *
       * <pre>
       * The port to start the maste daemon on. 
       * </pre>
       */
      public int getDaemonPort() {
        return daemonPort_;
      }
      /**
       * <code>required int32 daemon_port = 1;</code>
       *
       * <pre>
       * The port to start the maste daemon on. 
       * </pre>
       */
      public Builder setDaemonPort(int value) {
        bitField0_ |= 0x00000001;
        daemonPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 daemon_port = 1;</code>
       *
       * <pre>
       * The port to start the maste daemon on. 
       * </pre>
       */
      public Builder clearDaemonPort() {
        bitField0_ = (bitField0_ & ~0x00000001);
        daemonPort_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping> nodeMapping_ =
        java.util.Collections.emptyList();
      private void ensureNodeMappingIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          nodeMapping_ = new java.util.ArrayList<com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping>(nodeMapping_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder, com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder> nodeMappingBuilder_;

      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public java.util.List<com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping> getNodeMappingList() {
        if (nodeMappingBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodeMapping_);
        } else {
          return nodeMappingBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public int getNodeMappingCount() {
        if (nodeMappingBuilder_ == null) {
          return nodeMapping_.size();
        } else {
          return nodeMappingBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping getNodeMapping(int index) {
        if (nodeMappingBuilder_ == null) {
          return nodeMapping_.get(index);
        } else {
          return nodeMappingBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public Builder setNodeMapping(
          int index, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping value) {
        if (nodeMappingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeMappingIsMutable();
          nodeMapping_.set(index, value);
          onChanged();
        } else {
          nodeMappingBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public Builder setNodeMapping(
          int index, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder builderForValue) {
        if (nodeMappingBuilder_ == null) {
          ensureNodeMappingIsMutable();
          nodeMapping_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodeMappingBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public Builder addNodeMapping(com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping value) {
        if (nodeMappingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeMappingIsMutable();
          nodeMapping_.add(value);
          onChanged();
        } else {
          nodeMappingBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public Builder addNodeMapping(
          int index, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping value) {
        if (nodeMappingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeMappingIsMutable();
          nodeMapping_.add(index, value);
          onChanged();
        } else {
          nodeMappingBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public Builder addNodeMapping(
          com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder builderForValue) {
        if (nodeMappingBuilder_ == null) {
          ensureNodeMappingIsMutable();
          nodeMapping_.add(builderForValue.build());
          onChanged();
        } else {
          nodeMappingBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public Builder addNodeMapping(
          int index, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder builderForValue) {
        if (nodeMappingBuilder_ == null) {
          ensureNodeMappingIsMutable();
          nodeMapping_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodeMappingBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public Builder addAllNodeMapping(
          java.lang.Iterable<? extends com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping> values) {
        if (nodeMappingBuilder_ == null) {
          ensureNodeMappingIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodeMapping_);
          onChanged();
        } else {
          nodeMappingBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public Builder clearNodeMapping() {
        if (nodeMappingBuilder_ == null) {
          nodeMapping_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          nodeMappingBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public Builder removeNodeMapping(int index) {
        if (nodeMappingBuilder_ == null) {
          ensureNodeMappingIsMutable();
          nodeMapping_.remove(index);
          onChanged();
        } else {
          nodeMappingBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder getNodeMappingBuilder(
          int index) {
        return getNodeMappingFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder getNodeMappingOrBuilder(
          int index) {
        if (nodeMappingBuilder_ == null) {
          return nodeMapping_.get(index);  } else {
          return nodeMappingBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public java.util.List<? extends com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder> 
           getNodeMappingOrBuilderList() {
        if (nodeMappingBuilder_ != null) {
          return nodeMappingBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodeMapping_);
        }
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder addNodeMappingBuilder() {
        return getNodeMappingFieldBuilder().addBuilder(
            com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.getDefaultInstance());
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder addNodeMappingBuilder(
          int index) {
        return getNodeMappingFieldBuilder().addBuilder(
            index, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.getDefaultInstance());
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       *
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       */
      public java.util.List<com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder> 
           getNodeMappingBuilderList() {
        return getNodeMappingFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder, com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder> 
          getNodeMappingFieldBuilder() {
        if (nodeMappingBuilder_ == null) {
          nodeMappingBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder, com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder>(
                  nodeMapping_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          nodeMapping_ = null;
        }
        return nodeMappingBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.s13g.winston.master.proto.Config)
    }

    static {
      defaultInstance = new Config(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.s13g.winston.master.proto.Config)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_s13g_winston_master_proto_Config_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_s13g_winston_master_proto_Config_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_s13g_winston_master_proto_Config_NodeMapping_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_s13g_winston_master_proto_Config_NodeMapping_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036etc/protos/master_config.proto\022\035com.s1" +
      "3g.winston.master.proto\"\263\001\n\006Config\022\023\n\013da" +
      "emon_port\030\001 \002(\005\022G\n\014node_mapping\030\002 \003(\01321." +
      "com.s13g.winston.master.proto.Config.Nod" +
      "eMapping\032K\n\013NodeMapping\022\014\n\004name\030\001 \002(\t\022\017\n" +
      "\007address\030\002 \002(\t\022\014\n\004port\030\003 \002(\005\022\017\n\007use_ssl\030" +
      "\004 \002(\010B-\n\035com.s13g.winston.master.protoB\014" +
      "MasterProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_s13g_winston_master_proto_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_s13g_winston_master_proto_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_s13g_winston_master_proto_Config_descriptor,
        new java.lang.String[] { "DaemonPort", "NodeMapping", });
    internal_static_com_s13g_winston_master_proto_Config_NodeMapping_descriptor =
      internal_static_com_s13g_winston_master_proto_Config_descriptor.getNestedTypes().get(0);
    internal_static_com_s13g_winston_master_proto_Config_NodeMapping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_s13g_winston_master_proto_Config_NodeMapping_descriptor,
        new java.lang.String[] { "Name", "Address", "Port", "UseSsl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
