// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: etc/protos/node_config.proto

package com.s13g.winston.node.proto;

public final class NodeProtos {
  private NodeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.s13g.winston.master.proto.Config)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 daemon_port = 1;</code>
     *
     * <pre>
     * The port to start the node daemon on. 
     * </pre>
     */
    boolean hasDaemonPort();
    /**
     * <code>required int32 daemon_port = 1;</code>
     *
     * <pre>
     * The port to start the node daemon on. 
     * </pre>
     */
    int getDaemonPort();

    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
     *
     * <pre>
     * Which plugins are active on this node.
     * Note that the order matters if a plugin requires other plugins as their
     * dependency. Dependencies have to be available a this point.
     * Also we assume only one plugin of each type can be present.
     * </pre>
     */
    java.util.List<com.s13g.winston.node.proto.NodeProtos.Config.Plugin> 
        getActivePluginsList();
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
     *
     * <pre>
     * Which plugins are active on this node.
     * Note that the order matters if a plugin requires other plugins as their
     * dependency. Dependencies have to be available a this point.
     * Also we assume only one plugin of each type can be present.
     * </pre>
     */
    com.s13g.winston.node.proto.NodeProtos.Config.Plugin getActivePlugins(int index);
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
     *
     * <pre>
     * Which plugins are active on this node.
     * Note that the order matters if a plugin requires other plugins as their
     * dependency. Dependencies have to be available a this point.
     * Also we assume only one plugin of each type can be present.
     * </pre>
     */
    int getActivePluginsCount();
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
     *
     * <pre>
     * Which plugins are active on this node.
     * Note that the order matters if a plugin requires other plugins as their
     * dependency. Dependencies have to be available a this point.
     * Also we assume only one plugin of each type can be present.
     * </pre>
     */
    java.util.List<? extends com.s13g.winston.node.proto.NodeProtos.Config.PluginOrBuilder> 
        getActivePluginsOrBuilderList();
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
     *
     * <pre>
     * Which plugins are active on this node.
     * Note that the order matters if a plugin requires other plugins as their
     * dependency. Dependencies have to be available a this point.
     * Also we assume only one plugin of each type can be present.
     * </pre>
     */
    com.s13g.winston.node.proto.NodeProtos.Config.PluginOrBuilder getActivePluginsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.s13g.winston.master.proto.Config}
   *
   * <pre>
   * Configuration for the node daemon. 
   * </pre>
   */
  public static final class Config extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.s13g.winston.master.proto.Config)
      ConfigOrBuilder {
    // Use Config.newBuilder() to construct.
    private Config(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Config(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Config defaultInstance;
    public static Config getDefaultInstance() {
      return defaultInstance;
    }

    public Config getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Config(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              daemonPort_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                activePlugins_ = new java.util.ArrayList<com.s13g.winston.node.proto.NodeProtos.Config.Plugin>();
                mutable_bitField0_ |= 0x00000002;
              }
              activePlugins_.add(input.readMessage(com.s13g.winston.node.proto.NodeProtos.Config.Plugin.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          activePlugins_ = java.util.Collections.unmodifiableList(activePlugins_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.s13g.winston.node.proto.NodeProtos.internal_static_com_s13g_winston_master_proto_Config_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.s13g.winston.node.proto.NodeProtos.internal_static_com_s13g_winston_master_proto_Config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.s13g.winston.node.proto.NodeProtos.Config.class, com.s13g.winston.node.proto.NodeProtos.Config.Builder.class);
    }

    public static com.google.protobuf.Parser<Config> PARSER =
        new com.google.protobuf.AbstractParser<Config>() {
      public Config parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Config(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Config> getParserForType() {
      return PARSER;
    }

    public interface PluginOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.s13g.winston.master.proto.Config.Plugin)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * The name defines which plugin to loads. 
       * </pre>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * The name defines which plugin to loads. 
       * </pre>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * The name defines which plugin to loads. 
       * </pre>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>repeated int32 mapping = 2;</code>
       *
       * <pre>
       * Mapping from e.g. GPIO pins. 
       * </pre>
       */
      java.util.List<java.lang.Integer> getMappingList();
      /**
       * <code>repeated int32 mapping = 2;</code>
       *
       * <pre>
       * Mapping from e.g. GPIO pins. 
       * </pre>
       */
      int getMappingCount();
      /**
       * <code>repeated int32 mapping = 2;</code>
       *
       * <pre>
       * Mapping from e.g. GPIO pins. 
       * </pre>
       */
      int getMapping(int index);
    }
    /**
     * Protobuf type {@code com.s13g.winston.master.proto.Config.Plugin}
     *
     * <pre>
     * Defines a plugin that should be active on this node. 
     * </pre>
     */
    public static final class Plugin extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:com.s13g.winston.master.proto.Config.Plugin)
        PluginOrBuilder {
      // Use Plugin.newBuilder() to construct.
      private Plugin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Plugin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Plugin defaultInstance;
      public static Plugin getDefaultInstance() {
        return defaultInstance;
      }

      public Plugin getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Plugin(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                name_ = bs;
                break;
              }
              case 16: {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  mapping_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000002;
                }
                mapping_.add(input.readInt32());
                break;
              }
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                  mapping_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000002;
                }
                while (input.getBytesUntilLimit() > 0) {
                  mapping_.add(input.readInt32());
                }
                input.popLimit(limit);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            mapping_ = java.util.Collections.unmodifiableList(mapping_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.s13g.winston.node.proto.NodeProtos.internal_static_com_s13g_winston_master_proto_Config_Plugin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.s13g.winston.node.proto.NodeProtos.internal_static_com_s13g_winston_master_proto_Config_Plugin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.s13g.winston.node.proto.NodeProtos.Config.Plugin.class, com.s13g.winston.node.proto.NodeProtos.Config.Plugin.Builder.class);
      }

      public static com.google.protobuf.Parser<Plugin> PARSER =
          new com.google.protobuf.AbstractParser<Plugin>() {
        public Plugin parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Plugin(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Plugin> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * The name defines which plugin to loads. 
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * The name defines which plugin to loads. 
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * The name defines which plugin to loads. 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int MAPPING_FIELD_NUMBER = 2;
      private java.util.List<java.lang.Integer> mapping_;
      /**
       * <code>repeated int32 mapping = 2;</code>
       *
       * <pre>
       * Mapping from e.g. GPIO pins. 
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getMappingList() {
        return mapping_;
      }
      /**
       * <code>repeated int32 mapping = 2;</code>
       *
       * <pre>
       * Mapping from e.g. GPIO pins. 
       * </pre>
       */
      public int getMappingCount() {
        return mapping_.size();
      }
      /**
       * <code>repeated int32 mapping = 2;</code>
       *
       * <pre>
       * Mapping from e.g. GPIO pins. 
       * </pre>
       */
      public int getMapping(int index) {
        return mapping_.get(index);
      }

      private void initFields() {
        name_ = "";
        mapping_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        for (int i = 0; i < mapping_.size(); i++) {
          output.writeInt32(2, mapping_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        {
          int dataSize = 0;
          for (int i = 0; i < mapping_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(mapping_.get(i));
          }
          size += dataSize;
          size += 1 * getMappingList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.s13g.winston.node.proto.NodeProtos.Config.Plugin parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.s13g.winston.node.proto.NodeProtos.Config.Plugin parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.s13g.winston.node.proto.NodeProtos.Config.Plugin parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.s13g.winston.node.proto.NodeProtos.Config.Plugin parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.s13g.winston.node.proto.NodeProtos.Config.Plugin parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.s13g.winston.node.proto.NodeProtos.Config.Plugin parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.s13g.winston.node.proto.NodeProtos.Config.Plugin parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.s13g.winston.node.proto.NodeProtos.Config.Plugin parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.s13g.winston.node.proto.NodeProtos.Config.Plugin parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.s13g.winston.node.proto.NodeProtos.Config.Plugin parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.s13g.winston.node.proto.NodeProtos.Config.Plugin prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.s13g.winston.master.proto.Config.Plugin}
       *
       * <pre>
       * Defines a plugin that should be active on this node. 
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.s13g.winston.master.proto.Config.Plugin)
          com.s13g.winston.node.proto.NodeProtos.Config.PluginOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.s13g.winston.node.proto.NodeProtos.internal_static_com_s13g_winston_master_proto_Config_Plugin_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.s13g.winston.node.proto.NodeProtos.internal_static_com_s13g_winston_master_proto_Config_Plugin_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.s13g.winston.node.proto.NodeProtos.Config.Plugin.class, com.s13g.winston.node.proto.NodeProtos.Config.Plugin.Builder.class);
        }

        // Construct using com.s13g.winston.node.proto.NodeProtos.Config.Plugin.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          mapping_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.s13g.winston.node.proto.NodeProtos.internal_static_com_s13g_winston_master_proto_Config_Plugin_descriptor;
        }

        public com.s13g.winston.node.proto.NodeProtos.Config.Plugin getDefaultInstanceForType() {
          return com.s13g.winston.node.proto.NodeProtos.Config.Plugin.getDefaultInstance();
        }

        public com.s13g.winston.node.proto.NodeProtos.Config.Plugin build() {
          com.s13g.winston.node.proto.NodeProtos.Config.Plugin result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.s13g.winston.node.proto.NodeProtos.Config.Plugin buildPartial() {
          com.s13g.winston.node.proto.NodeProtos.Config.Plugin result = new com.s13g.winston.node.proto.NodeProtos.Config.Plugin(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            mapping_ = java.util.Collections.unmodifiableList(mapping_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.mapping_ = mapping_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.s13g.winston.node.proto.NodeProtos.Config.Plugin) {
            return mergeFrom((com.s13g.winston.node.proto.NodeProtos.Config.Plugin)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.s13g.winston.node.proto.NodeProtos.Config.Plugin other) {
          if (other == com.s13g.winston.node.proto.NodeProtos.Config.Plugin.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          if (!other.mapping_.isEmpty()) {
            if (mapping_.isEmpty()) {
              mapping_ = other.mapping_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMappingIsMutable();
              mapping_.addAll(other.mapping_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.s13g.winston.node.proto.NodeProtos.Config.Plugin parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.s13g.winston.node.proto.NodeProtos.Config.Plugin) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         *
         * <pre>
         * The name defines which plugin to loads. 
         * </pre>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         *
         * <pre>
         * The name defines which plugin to loads. 
         * </pre>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              name_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         *
         * <pre>
         * The name defines which plugin to loads. 
         * </pre>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         *
         * <pre>
         * The name defines which plugin to loads. 
         * </pre>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         *
         * <pre>
         * The name defines which plugin to loads. 
         * </pre>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         *
         * <pre>
         * The name defines which plugin to loads. 
         * </pre>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        private java.util.List<java.lang.Integer> mapping_ = java.util.Collections.emptyList();
        private void ensureMappingIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            mapping_ = new java.util.ArrayList<java.lang.Integer>(mapping_);
            bitField0_ |= 0x00000002;
           }
        }
        /**
         * <code>repeated int32 mapping = 2;</code>
         *
         * <pre>
         * Mapping from e.g. GPIO pins. 
         * </pre>
         */
        public java.util.List<java.lang.Integer>
            getMappingList() {
          return java.util.Collections.unmodifiableList(mapping_);
        }
        /**
         * <code>repeated int32 mapping = 2;</code>
         *
         * <pre>
         * Mapping from e.g. GPIO pins. 
         * </pre>
         */
        public int getMappingCount() {
          return mapping_.size();
        }
        /**
         * <code>repeated int32 mapping = 2;</code>
         *
         * <pre>
         * Mapping from e.g. GPIO pins. 
         * </pre>
         */
        public int getMapping(int index) {
          return mapping_.get(index);
        }
        /**
         * <code>repeated int32 mapping = 2;</code>
         *
         * <pre>
         * Mapping from e.g. GPIO pins. 
         * </pre>
         */
        public Builder setMapping(
            int index, int value) {
          ensureMappingIsMutable();
          mapping_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 mapping = 2;</code>
         *
         * <pre>
         * Mapping from e.g. GPIO pins. 
         * </pre>
         */
        public Builder addMapping(int value) {
          ensureMappingIsMutable();
          mapping_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 mapping = 2;</code>
         *
         * <pre>
         * Mapping from e.g. GPIO pins. 
         * </pre>
         */
        public Builder addAllMapping(
            java.lang.Iterable<? extends java.lang.Integer> values) {
          ensureMappingIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, mapping_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 mapping = 2;</code>
         *
         * <pre>
         * Mapping from e.g. GPIO pins. 
         * </pre>
         */
        public Builder clearMapping() {
          mapping_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.s13g.winston.master.proto.Config.Plugin)
      }

      static {
        defaultInstance = new Plugin(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.s13g.winston.master.proto.Config.Plugin)
    }

    private int bitField0_;
    public static final int DAEMON_PORT_FIELD_NUMBER = 1;
    private int daemonPort_;
    /**
     * <code>required int32 daemon_port = 1;</code>
     *
     * <pre>
     * The port to start the node daemon on. 
     * </pre>
     */
    public boolean hasDaemonPort() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 daemon_port = 1;</code>
     *
     * <pre>
     * The port to start the node daemon on. 
     * </pre>
     */
    public int getDaemonPort() {
      return daemonPort_;
    }

    public static final int ACTIVE_PLUGINS_FIELD_NUMBER = 2;
    private java.util.List<com.s13g.winston.node.proto.NodeProtos.Config.Plugin> activePlugins_;
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
     *
     * <pre>
     * Which plugins are active on this node.
     * Note that the order matters if a plugin requires other plugins as their
     * dependency. Dependencies have to be available a this point.
     * Also we assume only one plugin of each type can be present.
     * </pre>
     */
    public java.util.List<com.s13g.winston.node.proto.NodeProtos.Config.Plugin> getActivePluginsList() {
      return activePlugins_;
    }
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
     *
     * <pre>
     * Which plugins are active on this node.
     * Note that the order matters if a plugin requires other plugins as their
     * dependency. Dependencies have to be available a this point.
     * Also we assume only one plugin of each type can be present.
     * </pre>
     */
    public java.util.List<? extends com.s13g.winston.node.proto.NodeProtos.Config.PluginOrBuilder> 
        getActivePluginsOrBuilderList() {
      return activePlugins_;
    }
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
     *
     * <pre>
     * Which plugins are active on this node.
     * Note that the order matters if a plugin requires other plugins as their
     * dependency. Dependencies have to be available a this point.
     * Also we assume only one plugin of each type can be present.
     * </pre>
     */
    public int getActivePluginsCount() {
      return activePlugins_.size();
    }
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
     *
     * <pre>
     * Which plugins are active on this node.
     * Note that the order matters if a plugin requires other plugins as their
     * dependency. Dependencies have to be available a this point.
     * Also we assume only one plugin of each type can be present.
     * </pre>
     */
    public com.s13g.winston.node.proto.NodeProtos.Config.Plugin getActivePlugins(int index) {
      return activePlugins_.get(index);
    }
    /**
     * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
     *
     * <pre>
     * Which plugins are active on this node.
     * Note that the order matters if a plugin requires other plugins as their
     * dependency. Dependencies have to be available a this point.
     * Also we assume only one plugin of each type can be present.
     * </pre>
     */
    public com.s13g.winston.node.proto.NodeProtos.Config.PluginOrBuilder getActivePluginsOrBuilder(
        int index) {
      return activePlugins_.get(index);
    }

    private void initFields() {
      daemonPort_ = 0;
      activePlugins_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDaemonPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getActivePluginsCount(); i++) {
        if (!getActivePlugins(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, daemonPort_);
      }
      for (int i = 0; i < activePlugins_.size(); i++) {
        output.writeMessage(2, activePlugins_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, daemonPort_);
      }
      for (int i = 0; i < activePlugins_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, activePlugins_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.s13g.winston.node.proto.NodeProtos.Config parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.s13g.winston.node.proto.NodeProtos.Config parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.s13g.winston.node.proto.NodeProtos.Config parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.s13g.winston.node.proto.NodeProtos.Config parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.s13g.winston.node.proto.NodeProtos.Config parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.s13g.winston.node.proto.NodeProtos.Config parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.s13g.winston.node.proto.NodeProtos.Config parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.s13g.winston.node.proto.NodeProtos.Config parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.s13g.winston.node.proto.NodeProtos.Config parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.s13g.winston.node.proto.NodeProtos.Config parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.s13g.winston.node.proto.NodeProtos.Config prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.s13g.winston.master.proto.Config}
     *
     * <pre>
     * Configuration for the node daemon. 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.s13g.winston.master.proto.Config)
        com.s13g.winston.node.proto.NodeProtos.ConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.s13g.winston.node.proto.NodeProtos.internal_static_com_s13g_winston_master_proto_Config_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.s13g.winston.node.proto.NodeProtos.internal_static_com_s13g_winston_master_proto_Config_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.s13g.winston.node.proto.NodeProtos.Config.class, com.s13g.winston.node.proto.NodeProtos.Config.Builder.class);
      }

      // Construct using com.s13g.winston.node.proto.NodeProtos.Config.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getActivePluginsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        daemonPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (activePluginsBuilder_ == null) {
          activePlugins_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          activePluginsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.s13g.winston.node.proto.NodeProtos.internal_static_com_s13g_winston_master_proto_Config_descriptor;
      }

      public com.s13g.winston.node.proto.NodeProtos.Config getDefaultInstanceForType() {
        return com.s13g.winston.node.proto.NodeProtos.Config.getDefaultInstance();
      }

      public com.s13g.winston.node.proto.NodeProtos.Config build() {
        com.s13g.winston.node.proto.NodeProtos.Config result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.s13g.winston.node.proto.NodeProtos.Config buildPartial() {
        com.s13g.winston.node.proto.NodeProtos.Config result = new com.s13g.winston.node.proto.NodeProtos.Config(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.daemonPort_ = daemonPort_;
        if (activePluginsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            activePlugins_ = java.util.Collections.unmodifiableList(activePlugins_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.activePlugins_ = activePlugins_;
        } else {
          result.activePlugins_ = activePluginsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.s13g.winston.node.proto.NodeProtos.Config) {
          return mergeFrom((com.s13g.winston.node.proto.NodeProtos.Config)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.s13g.winston.node.proto.NodeProtos.Config other) {
        if (other == com.s13g.winston.node.proto.NodeProtos.Config.getDefaultInstance()) return this;
        if (other.hasDaemonPort()) {
          setDaemonPort(other.getDaemonPort());
        }
        if (activePluginsBuilder_ == null) {
          if (!other.activePlugins_.isEmpty()) {
            if (activePlugins_.isEmpty()) {
              activePlugins_ = other.activePlugins_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureActivePluginsIsMutable();
              activePlugins_.addAll(other.activePlugins_);
            }
            onChanged();
          }
        } else {
          if (!other.activePlugins_.isEmpty()) {
            if (activePluginsBuilder_.isEmpty()) {
              activePluginsBuilder_.dispose();
              activePluginsBuilder_ = null;
              activePlugins_ = other.activePlugins_;
              bitField0_ = (bitField0_ & ~0x00000002);
              activePluginsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getActivePluginsFieldBuilder() : null;
            } else {
              activePluginsBuilder_.addAllMessages(other.activePlugins_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDaemonPort()) {
          
          return false;
        }
        for (int i = 0; i < getActivePluginsCount(); i++) {
          if (!getActivePlugins(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.s13g.winston.node.proto.NodeProtos.Config parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.s13g.winston.node.proto.NodeProtos.Config) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int daemonPort_ ;
      /**
       * <code>required int32 daemon_port = 1;</code>
       *
       * <pre>
       * The port to start the node daemon on. 
       * </pre>
       */
      public boolean hasDaemonPort() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 daemon_port = 1;</code>
       *
       * <pre>
       * The port to start the node daemon on. 
       * </pre>
       */
      public int getDaemonPort() {
        return daemonPort_;
      }
      /**
       * <code>required int32 daemon_port = 1;</code>
       *
       * <pre>
       * The port to start the node daemon on. 
       * </pre>
       */
      public Builder setDaemonPort(int value) {
        bitField0_ |= 0x00000001;
        daemonPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 daemon_port = 1;</code>
       *
       * <pre>
       * The port to start the node daemon on. 
       * </pre>
       */
      public Builder clearDaemonPort() {
        bitField0_ = (bitField0_ & ~0x00000001);
        daemonPort_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.s13g.winston.node.proto.NodeProtos.Config.Plugin> activePlugins_ =
        java.util.Collections.emptyList();
      private void ensureActivePluginsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          activePlugins_ = new java.util.ArrayList<com.s13g.winston.node.proto.NodeProtos.Config.Plugin>(activePlugins_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.s13g.winston.node.proto.NodeProtos.Config.Plugin, com.s13g.winston.node.proto.NodeProtos.Config.Plugin.Builder, com.s13g.winston.node.proto.NodeProtos.Config.PluginOrBuilder> activePluginsBuilder_;

      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public java.util.List<com.s13g.winston.node.proto.NodeProtos.Config.Plugin> getActivePluginsList() {
        if (activePluginsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(activePlugins_);
        } else {
          return activePluginsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public int getActivePluginsCount() {
        if (activePluginsBuilder_ == null) {
          return activePlugins_.size();
        } else {
          return activePluginsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public com.s13g.winston.node.proto.NodeProtos.Config.Plugin getActivePlugins(int index) {
        if (activePluginsBuilder_ == null) {
          return activePlugins_.get(index);
        } else {
          return activePluginsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public Builder setActivePlugins(
          int index, com.s13g.winston.node.proto.NodeProtos.Config.Plugin value) {
        if (activePluginsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActivePluginsIsMutable();
          activePlugins_.set(index, value);
          onChanged();
        } else {
          activePluginsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public Builder setActivePlugins(
          int index, com.s13g.winston.node.proto.NodeProtos.Config.Plugin.Builder builderForValue) {
        if (activePluginsBuilder_ == null) {
          ensureActivePluginsIsMutable();
          activePlugins_.set(index, builderForValue.build());
          onChanged();
        } else {
          activePluginsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public Builder addActivePlugins(com.s13g.winston.node.proto.NodeProtos.Config.Plugin value) {
        if (activePluginsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActivePluginsIsMutable();
          activePlugins_.add(value);
          onChanged();
        } else {
          activePluginsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public Builder addActivePlugins(
          int index, com.s13g.winston.node.proto.NodeProtos.Config.Plugin value) {
        if (activePluginsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActivePluginsIsMutable();
          activePlugins_.add(index, value);
          onChanged();
        } else {
          activePluginsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public Builder addActivePlugins(
          com.s13g.winston.node.proto.NodeProtos.Config.Plugin.Builder builderForValue) {
        if (activePluginsBuilder_ == null) {
          ensureActivePluginsIsMutable();
          activePlugins_.add(builderForValue.build());
          onChanged();
        } else {
          activePluginsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public Builder addActivePlugins(
          int index, com.s13g.winston.node.proto.NodeProtos.Config.Plugin.Builder builderForValue) {
        if (activePluginsBuilder_ == null) {
          ensureActivePluginsIsMutable();
          activePlugins_.add(index, builderForValue.build());
          onChanged();
        } else {
          activePluginsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public Builder addAllActivePlugins(
          java.lang.Iterable<? extends com.s13g.winston.node.proto.NodeProtos.Config.Plugin> values) {
        if (activePluginsBuilder_ == null) {
          ensureActivePluginsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, activePlugins_);
          onChanged();
        } else {
          activePluginsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public Builder clearActivePlugins() {
        if (activePluginsBuilder_ == null) {
          activePlugins_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          activePluginsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public Builder removeActivePlugins(int index) {
        if (activePluginsBuilder_ == null) {
          ensureActivePluginsIsMutable();
          activePlugins_.remove(index);
          onChanged();
        } else {
          activePluginsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public com.s13g.winston.node.proto.NodeProtos.Config.Plugin.Builder getActivePluginsBuilder(
          int index) {
        return getActivePluginsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public com.s13g.winston.node.proto.NodeProtos.Config.PluginOrBuilder getActivePluginsOrBuilder(
          int index) {
        if (activePluginsBuilder_ == null) {
          return activePlugins_.get(index);  } else {
          return activePluginsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public java.util.List<? extends com.s13g.winston.node.proto.NodeProtos.Config.PluginOrBuilder> 
           getActivePluginsOrBuilderList() {
        if (activePluginsBuilder_ != null) {
          return activePluginsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(activePlugins_);
        }
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public com.s13g.winston.node.proto.NodeProtos.Config.Plugin.Builder addActivePluginsBuilder() {
        return getActivePluginsFieldBuilder().addBuilder(
            com.s13g.winston.node.proto.NodeProtos.Config.Plugin.getDefaultInstance());
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public com.s13g.winston.node.proto.NodeProtos.Config.Plugin.Builder addActivePluginsBuilder(
          int index) {
        return getActivePluginsFieldBuilder().addBuilder(
            index, com.s13g.winston.node.proto.NodeProtos.Config.Plugin.getDefaultInstance());
      }
      /**
       * <code>repeated .com.s13g.winston.master.proto.Config.Plugin active_plugins = 2;</code>
       *
       * <pre>
       * Which plugins are active on this node.
       * Note that the order matters if a plugin requires other plugins as their
       * dependency. Dependencies have to be available a this point.
       * Also we assume only one plugin of each type can be present.
       * </pre>
       */
      public java.util.List<com.s13g.winston.node.proto.NodeProtos.Config.Plugin.Builder> 
           getActivePluginsBuilderList() {
        return getActivePluginsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.s13g.winston.node.proto.NodeProtos.Config.Plugin, com.s13g.winston.node.proto.NodeProtos.Config.Plugin.Builder, com.s13g.winston.node.proto.NodeProtos.Config.PluginOrBuilder> 
          getActivePluginsFieldBuilder() {
        if (activePluginsBuilder_ == null) {
          activePluginsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.s13g.winston.node.proto.NodeProtos.Config.Plugin, com.s13g.winston.node.proto.NodeProtos.Config.Plugin.Builder, com.s13g.winston.node.proto.NodeProtos.Config.PluginOrBuilder>(
                  activePlugins_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          activePlugins_ = null;
        }
        return activePluginsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.s13g.winston.master.proto.Config)
    }

    static {
      defaultInstance = new Config(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.s13g.winston.master.proto.Config)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_s13g_winston_master_proto_Config_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_s13g_winston_master_proto_Config_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_s13g_winston_master_proto_Config_Plugin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_s13g_winston_master_proto_Config_Plugin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034etc/protos/node_config.proto\022\035com.s13g" +
      ".winston.master.proto\"\214\001\n\006Config\022\023\n\013daem" +
      "on_port\030\001 \002(\005\022D\n\016active_plugins\030\002 \003(\0132,." +
      "com.s13g.winston.master.proto.Config.Plu" +
      "gin\032\'\n\006Plugin\022\014\n\004name\030\001 \002(\t\022\017\n\007mapping\030\002" +
      " \003(\005B)\n\033com.s13g.winston.node.protoB\nNod" +
      "eProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_s13g_winston_master_proto_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_s13g_winston_master_proto_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_s13g_winston_master_proto_Config_descriptor,
        new java.lang.String[] { "DaemonPort", "ActivePlugins", });
    internal_static_com_s13g_winston_master_proto_Config_Plugin_descriptor =
      internal_static_com_s13g_winston_master_proto_Config_descriptor.getNestedTypes().get(0);
    internal_static_com_s13g_winston_master_proto_Config_Plugin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_s13g_winston_master_proto_Config_Plugin_descriptor,
        new java.lang.String[] { "Name", "Mapping", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
