// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: etc/protocolbuffers/gpio_proxy.proto

package com.s13g.winston.lib.pi4jproxy.proto;

public final class GpioProxyProtos {
  private GpioProxyProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GpioRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.s13g.winston.lib.pi4jproxy.proto.GpioRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string command = 1;</code>
     */
    boolean hasCommand();
    /**
     * <code>required string command = 1;</code>
     */
    java.lang.String getCommand();
    /**
     * <code>required string command = 1;</code>
     */
    com.google.protobuf.ByteString
        getCommandBytes();

    /**
     * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
     */
    java.util.List<com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param> 
        getParamsList();
    /**
     * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
     */
    com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param getParams(int index);
    /**
     * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
     */
    int getParamsCount();
    /**
     * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
     */
    java.util.List<? extends com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.ParamOrBuilder> 
        getParamsOrBuilderList();
    /**
     * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
     */
    com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.ParamOrBuilder getParamsOrBuilder(
        int index);

    /**
     * <code>optional string email = 3;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();
  }
  /**
   * Protobuf type {@code com.s13g.winston.lib.pi4jproxy.proto.GpioRequest}
   */
  public static final class GpioRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.s13g.winston.lib.pi4jproxy.proto.GpioRequest)
      GpioRequestOrBuilder {
    // Use GpioRequest.newBuilder() to construct.
    private GpioRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GpioRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GpioRequest defaultInstance;
    public static GpioRequest getDefaultInstance() {
      return defaultInstance;
    }

    public GpioRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GpioRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              command_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                params_ = new java.util.ArrayList<com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param>();
                mutable_bitField0_ |= 0x00000002;
              }
              params_.add(input.readMessage(com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              email_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          params_ = java.util.Collections.unmodifiableList(params_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.class, com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<GpioRequest> PARSER =
        new com.google.protobuf.AbstractParser<GpioRequest>() {
      public GpioRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GpioRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GpioRequest> getParserForType() {
      return PARSER;
    }

    public interface ParamOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string type = 1;</code>
       */
      boolean hasType();
      /**
       * <code>required string type = 1;</code>
       */
      java.lang.String getType();
      /**
       * <code>required string type = 1;</code>
       */
      com.google.protobuf.ByteString
          getTypeBytes();

      /**
       * <code>required string value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>required string value = 2;</code>
       */
      java.lang.String getValue();
      /**
       * <code>required string value = 2;</code>
       */
      com.google.protobuf.ByteString
          getValueBytes();
    }
    /**
     * Protobuf type {@code com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param}
     */
    public static final class Param extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param)
        ParamOrBuilder {
      // Use Param.newBuilder() to construct.
      private Param(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Param(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Param defaultInstance;
      public static Param getDefaultInstance() {
        return defaultInstance;
      }

      public Param getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Param(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                type_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                value_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_Param_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_Param_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.class, com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.Builder.class);
      }

      public static com.google.protobuf.Parser<Param> PARSER =
          new com.google.protobuf.AbstractParser<Param>() {
        public Param parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Param(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Param> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int TYPE_FIELD_NUMBER = 1;
      private java.lang.Object type_;
      /**
       * <code>required string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private java.lang.Object value_;
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        type_ = "";
        value_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getTypeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getValueBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getTypeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getValueBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param)
          com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.ParamOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_Param_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_Param_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.class, com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.Builder.class);
        }

        // Construct using com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          type_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_Param_descriptor;
        }

        public com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param getDefaultInstanceForType() {
          return com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.getDefaultInstance();
        }

        public com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param build() {
          com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param buildPartial() {
          com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param result = new com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param) {
            return mergeFrom((com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param other) {
          if (other == com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.getDefaultInstance()) return this;
          if (other.hasType()) {
            bitField0_ |= 0x00000001;
            type_ = other.type_;
            onChanged();
          }
          if (other.hasValue()) {
            bitField0_ |= 0x00000002;
            value_ = other.value_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasType()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object type_ = "";
        /**
         * <code>required string type = 1;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string type = 1;</code>
         */
        public java.lang.String getType() {
          java.lang.Object ref = type_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              type_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string type = 1;</code>
         */
        public com.google.protobuf.ByteString
            getTypeBytes() {
          java.lang.Object ref = type_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            type_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string type = 1;</code>
         */
        public Builder setType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string type = 1;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = getDefaultInstance().getType();
          onChanged();
          return this;
        }
        /**
         * <code>required string type = 1;</code>
         */
        public Builder setTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object value_ = "";
        /**
         * <code>required string value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string value = 2;</code>
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              value_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string value = 2;</code>
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param)
      }

      static {
        defaultInstance = new Param(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param)
    }

    private int bitField0_;
    public static final int COMMAND_FIELD_NUMBER = 1;
    private java.lang.Object command_;
    /**
     * <code>required string command = 1;</code>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string command = 1;</code>
     */
    public java.lang.String getCommand() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          command_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string command = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMS_FIELD_NUMBER = 2;
    private java.util.List<com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param> params_;
    /**
     * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
     */
    public java.util.List<com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param> getParamsList() {
      return params_;
    }
    /**
     * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
     */
    public java.util.List<? extends com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.ParamOrBuilder> 
        getParamsOrBuilderList() {
      return params_;
    }
    /**
     * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
     */
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
     */
    public com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param getParams(int index) {
      return params_.get(index);
    }
    /**
     * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
     */
    public com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.ParamOrBuilder getParamsOrBuilder(
        int index) {
      return params_.get(index);
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    /**
     * <code>optional string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      command_ = "";
      params_ = java.util.Collections.emptyList();
      email_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getParamsCount(); i++) {
        if (!getParams(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCommandBytes());
      }
      for (int i = 0; i < params_.size(); i++) {
        output.writeMessage(2, params_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getEmailBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCommandBytes());
      }
      for (int i = 0; i < params_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, params_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.s13g.winston.lib.pi4jproxy.proto.GpioRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.s13g.winston.lib.pi4jproxy.proto.GpioRequest)
        com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.class, com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Builder.class);
      }

      // Construct using com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getParamsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        command_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (paramsBuilder_ == null) {
          params_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          paramsBuilder_.clear();
        }
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_descriptor;
      }

      public com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest getDefaultInstanceForType() {
        return com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.getDefaultInstance();
      }

      public com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest build() {
        com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest buildPartial() {
        com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest result = new com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.command_ = command_;
        if (paramsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            params_ = java.util.Collections.unmodifiableList(params_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.params_ = params_;
        } else {
          result.params_ = paramsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.email_ = email_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest) {
          return mergeFrom((com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest other) {
        if (other == com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.getDefaultInstance()) return this;
        if (other.hasCommand()) {
          bitField0_ |= 0x00000001;
          command_ = other.command_;
          onChanged();
        }
        if (paramsBuilder_ == null) {
          if (!other.params_.isEmpty()) {
            if (params_.isEmpty()) {
              params_ = other.params_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureParamsIsMutable();
              params_.addAll(other.params_);
            }
            onChanged();
          }
        } else {
          if (!other.params_.isEmpty()) {
            if (paramsBuilder_.isEmpty()) {
              paramsBuilder_.dispose();
              paramsBuilder_ = null;
              params_ = other.params_;
              bitField0_ = (bitField0_ & ~0x00000002);
              paramsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getParamsFieldBuilder() : null;
            } else {
              paramsBuilder_.addAllMessages(other.params_);
            }
          }
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCommand()) {
          
          return false;
        }
        for (int i = 0; i < getParamsCount(); i++) {
          if (!getParams(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object command_ = "";
      /**
       * <code>required string command = 1;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string command = 1;</code>
       */
      public java.lang.String getCommand() {
        java.lang.Object ref = command_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            command_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string command = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCommandBytes() {
        java.lang.Object ref = command_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          command_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string command = 1;</code>
       */
      public Builder setCommand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string command = 1;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = getDefaultInstance().getCommand();
        onChanged();
        return this;
      }
      /**
       * <code>required string command = 1;</code>
       */
      public Builder setCommandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        command_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param> params_ =
        java.util.Collections.emptyList();
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          params_ = new java.util.ArrayList<com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param>(params_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param, com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.Builder, com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.ParamOrBuilder> paramsBuilder_;

      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public java.util.List<com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param> getParamsList() {
        if (paramsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(params_);
        } else {
          return paramsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public int getParamsCount() {
        if (paramsBuilder_ == null) {
          return params_.size();
        } else {
          return paramsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param getParams(int index) {
        if (paramsBuilder_ == null) {
          return params_.get(index);
        } else {
          return paramsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public Builder setParams(
          int index, com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.set(index, value);
          onChanged();
        } else {
          paramsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public Builder setParams(
          int index, com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.set(index, builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public Builder addParams(com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.add(value);
          onChanged();
        } else {
          paramsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public Builder addParams(
          int index, com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.add(index, value);
          onChanged();
        } else {
          paramsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public Builder addParams(
          com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.add(builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public Builder addParams(
          int index, com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.add(index, builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public Builder addAllParams(
          java.lang.Iterable<? extends com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param> values) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, params_);
          onChanged();
        } else {
          paramsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public Builder clearParams() {
        if (paramsBuilder_ == null) {
          params_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          paramsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public Builder removeParams(int index) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.remove(index);
          onChanged();
        } else {
          paramsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.Builder getParamsBuilder(
          int index) {
        return getParamsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.ParamOrBuilder getParamsOrBuilder(
          int index) {
        if (paramsBuilder_ == null) {
          return params_.get(index);  } else {
          return paramsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public java.util.List<? extends com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.ParamOrBuilder> 
           getParamsOrBuilderList() {
        if (paramsBuilder_ != null) {
          return paramsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(params_);
        }
      }
      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.Builder addParamsBuilder() {
        return getParamsFieldBuilder().addBuilder(
            com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.getDefaultInstance());
      }
      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.Builder addParamsBuilder(
          int index) {
        return getParamsFieldBuilder().addBuilder(
            index, com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.getDefaultInstance());
      }
      /**
       * <code>repeated .com.s13g.winston.lib.pi4jproxy.proto.GpioRequest.Param params = 2;</code>
       */
      public java.util.List<com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.Builder> 
           getParamsBuilderList() {
        return getParamsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param, com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.Builder, com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.ParamOrBuilder> 
          getParamsFieldBuilder() {
        if (paramsBuilder_ == null) {
          paramsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param, com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.Param.Builder, com.s13g.winston.lib.pi4jproxy.proto.GpioProxyProtos.GpioRequest.ParamOrBuilder>(
                  params_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          params_ = null;
        }
        return paramsBuilder_;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 3;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            email_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.s13g.winston.lib.pi4jproxy.proto.GpioRequest)
    }

    static {
      defaultInstance = new GpioRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.s13g.winston.lib.pi4jproxy.proto.GpioRequest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_Param_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_Param_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$etc/protocolbuffers/gpio_proxy.proto\022$" +
      "com.s13g.winston.lib.pi4jproxy.proto\"\234\001\n" +
      "\013GpioRequest\022\017\n\007command\030\001 \002(\t\022G\n\006params\030" +
      "\002 \003(\01327.com.s13g.winston.lib.pi4jproxy.p" +
      "roto.GpioRequest.Param\022\r\n\005email\030\003 \001(\t\032$\n" +
      "\005Param\022\014\n\004type\030\001 \002(\t\022\r\n\005value\030\002 \002(\tB7\n$c" +
      "om.s13g.winston.lib.pi4jproxy.protoB\017Gpi" +
      "oProxyProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_descriptor,
        new java.lang.String[] { "Command", "Params", "Email", });
    internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_Param_descriptor =
      internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_Param_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_s13g_winston_lib_pi4jproxy_proto_GpioRequest_Param_descriptor,
        new java.lang.String[] { "Type", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
