// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: etc/protos/master_config.proto

package com.s13g.winston.master.proto;

public final class MasterProtos {
  private MasterProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.s13g.winston.master.proto.Config)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The port to start the master daemon on. 
     * </pre>
     *
     * <code>optional int32 daemon_port = 1;</code>
     */
    int getDaemonPort();

    /**
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     */
    java.util.List<com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping> 
        getNodeMappingList();
    /**
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     */
    com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping getNodeMapping(int index);
    /**
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     */
    int getNodeMappingCount();
    /**
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     */
    java.util.List<? extends com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder> 
        getNodeMappingOrBuilderList();
    /**
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     */
    com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder getNodeMappingOrBuilder(
        int index);
  }
  /**
   * <pre>
   * Configuration for the master daemon. 
   * </pre>
   *
   * Protobuf type {@code com.s13g.winston.master.proto.Config}
   */
  public  static final class Config extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.s13g.winston.master.proto.Config)
      ConfigOrBuilder {
    // Use Config.newBuilder() to construct.
    private Config(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Config() {
      daemonPort_ = 0;
      nodeMapping_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Config(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              daemonPort_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                nodeMapping_ = new java.util.ArrayList<com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping>();
                mutable_bitField0_ |= 0x00000002;
              }
              nodeMapping_.add(
                  input.readMessage(com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          nodeMapping_ = java.util.Collections.unmodifiableList(nodeMapping_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.s13g.winston.master.proto.MasterProtos.Config.class, com.s13g.winston.master.proto.MasterProtos.Config.Builder.class);
    }

    public interface NodeMappingOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.s13g.winston.master.proto.Config.NodeMapping)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * Name of the node, like "pi-garage". 
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <pre>
       * Name of the node, like "pi-garage". 
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <pre>
       * The IP address of the node. 
       * </pre>
       *
       * <code>optional string address = 2;</code>
       */
      java.lang.String getAddress();
      /**
       * <pre>
       * The IP address of the node. 
       * </pre>
       *
       * <code>optional string address = 2;</code>
       */
      com.google.protobuf.ByteString
          getAddressBytes();

      /**
       * <pre>
       * The port to access the node daemon, typically 1984. 
       * </pre>
       *
       * <code>optional int32 port = 3;</code>
       */
      int getPort();

      /**
       * <pre>
       * Whether the node daemon should accessed through https. 
       * </pre>
       *
       * <code>optional bool use_ssl = 4;</code>
       */
      boolean getUseSsl();
    }
    /**
     * <pre>
     * Mapping from tag to node. 
     * </pre>
     *
     * Protobuf type {@code com.s13g.winston.master.proto.Config.NodeMapping}
     */
    public  static final class NodeMapping extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.s13g.winston.master.proto.Config.NodeMapping)
        NodeMappingOrBuilder {
      // Use NodeMapping.newBuilder() to construct.
      private NodeMapping(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private NodeMapping() {
        name_ = "";
        address_ = "";
        port_ = 0;
        useSsl_ = false;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private NodeMapping(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                address_ = s;
                break;
              }
              case 24: {

                port_ = input.readInt32();
                break;
              }
              case 32: {

                useSsl_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_NodeMapping_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_NodeMapping_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.class, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder.class);
      }

      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <pre>
       * Name of the node, like "pi-garage". 
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * Name of the node, like "pi-garage". 
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ADDRESS_FIELD_NUMBER = 2;
      private volatile java.lang.Object address_;
      /**
       * <pre>
       * The IP address of the node. 
       * </pre>
       *
       * <code>optional string address = 2;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * The IP address of the node. 
       * </pre>
       *
       * <code>optional string address = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PORT_FIELD_NUMBER = 3;
      private int port_;
      /**
       * <pre>
       * The port to access the node daemon, typically 1984. 
       * </pre>
       *
       * <code>optional int32 port = 3;</code>
       */
      public int getPort() {
        return port_;
      }

      public static final int USE_SSL_FIELD_NUMBER = 4;
      private boolean useSsl_;
      /**
       * <pre>
       * Whether the node daemon should accessed through https. 
       * </pre>
       *
       * <code>optional bool use_ssl = 4;</code>
       */
      public boolean getUseSsl() {
        return useSsl_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        if (!getAddressBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, address_);
        }
        if (port_ != 0) {
          output.writeInt32(3, port_);
        }
        if (useSsl_ != false) {
          output.writeBool(4, useSsl_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        if (!getAddressBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, address_);
        }
        if (port_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, port_);
        }
        if (useSsl_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(4, useSsl_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping)) {
          return super.equals(obj);
        }
        com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping other = (com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping) obj;

        boolean result = true;
        result = result && getName()
            .equals(other.getName());
        result = result && getAddress()
            .equals(other.getAddress());
        result = result && (getPort()
            == other.getPort());
        result = result && (getUseSsl()
            == other.getUseSsl());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
        hash = (37 * hash) + PORT_FIELD_NUMBER;
        hash = (53 * hash) + getPort();
        hash = (37 * hash) + USE_SSL_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getUseSsl());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * Mapping from tag to node. 
       * </pre>
       *
       * Protobuf type {@code com.s13g.winston.master.proto.Config.NodeMapping}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.s13g.winston.master.proto.Config.NodeMapping)
          com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_NodeMapping_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_NodeMapping_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.class, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder.class);
        }

        // Construct using com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          name_ = "";

          address_ = "";

          port_ = 0;

          useSsl_ = false;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_NodeMapping_descriptor;
        }

        public com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping getDefaultInstanceForType() {
          return com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.getDefaultInstance();
        }

        public com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping build() {
          com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping buildPartial() {
          com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping result = new com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping(this);
          result.name_ = name_;
          result.address_ = address_;
          result.port_ = port_;
          result.useSsl_ = useSsl_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping) {
            return mergeFrom((com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping other) {
          if (other == com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (!other.getAddress().isEmpty()) {
            address_ = other.address_;
            onChanged();
          }
          if (other.getPort() != 0) {
            setPort(other.getPort());
          }
          if (other.getUseSsl() != false) {
            setUseSsl(other.getUseSsl());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <pre>
         * Name of the node, like "pi-garage". 
         * </pre>
         *
         * <code>optional string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * Name of the node, like "pi-garage". 
         * </pre>
         *
         * <code>optional string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * Name of the node, like "pi-garage". 
         * </pre>
         *
         * <code>optional string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Name of the node, like "pi-garage". 
         * </pre>
         *
         * <code>optional string name = 1;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Name of the node, like "pi-garage". 
         * </pre>
         *
         * <code>optional string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object address_ = "";
        /**
         * <pre>
         * The IP address of the node. 
         * </pre>
         *
         * <code>optional string address = 2;</code>
         */
        public java.lang.String getAddress() {
          java.lang.Object ref = address_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            address_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * The IP address of the node. 
         * </pre>
         *
         * <code>optional string address = 2;</code>
         */
        public com.google.protobuf.ByteString
            getAddressBytes() {
          java.lang.Object ref = address_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            address_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * The IP address of the node. 
         * </pre>
         *
         * <code>optional string address = 2;</code>
         */
        public Builder setAddress(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          address_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * The IP address of the node. 
         * </pre>
         *
         * <code>optional string address = 2;</code>
         */
        public Builder clearAddress() {
          
          address_ = getDefaultInstance().getAddress();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * The IP address of the node. 
         * </pre>
         *
         * <code>optional string address = 2;</code>
         */
        public Builder setAddressBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          address_ = value;
          onChanged();
          return this;
        }

        private int port_ ;
        /**
         * <pre>
         * The port to access the node daemon, typically 1984. 
         * </pre>
         *
         * <code>optional int32 port = 3;</code>
         */
        public int getPort() {
          return port_;
        }
        /**
         * <pre>
         * The port to access the node daemon, typically 1984. 
         * </pre>
         *
         * <code>optional int32 port = 3;</code>
         */
        public Builder setPort(int value) {
          
          port_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * The port to access the node daemon, typically 1984. 
         * </pre>
         *
         * <code>optional int32 port = 3;</code>
         */
        public Builder clearPort() {
          
          port_ = 0;
          onChanged();
          return this;
        }

        private boolean useSsl_ ;
        /**
         * <pre>
         * Whether the node daemon should accessed through https. 
         * </pre>
         *
         * <code>optional bool use_ssl = 4;</code>
         */
        public boolean getUseSsl() {
          return useSsl_;
        }
        /**
         * <pre>
         * Whether the node daemon should accessed through https. 
         * </pre>
         *
         * <code>optional bool use_ssl = 4;</code>
         */
        public Builder setUseSsl(boolean value) {
          
          useSsl_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Whether the node daemon should accessed through https. 
         * </pre>
         *
         * <code>optional bool use_ssl = 4;</code>
         */
        public Builder clearUseSsl() {
          
          useSsl_ = false;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:com.s13g.winston.master.proto.Config.NodeMapping)
      }

      // @@protoc_insertion_point(class_scope:com.s13g.winston.master.proto.Config.NodeMapping)
      private static final com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping();
      }

      public static com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<NodeMapping>
          PARSER = new com.google.protobuf.AbstractParser<NodeMapping>() {
        public NodeMapping parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new NodeMapping(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<NodeMapping> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<NodeMapping> getParserForType() {
        return PARSER;
      }

      public com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int DAEMON_PORT_FIELD_NUMBER = 1;
    private int daemonPort_;
    /**
     * <pre>
     * The port to start the master daemon on. 
     * </pre>
     *
     * <code>optional int32 daemon_port = 1;</code>
     */
    public int getDaemonPort() {
      return daemonPort_;
    }

    public static final int NODE_MAPPING_FIELD_NUMBER = 2;
    private java.util.List<com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping> nodeMapping_;
    /**
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     */
    public java.util.List<com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping> getNodeMappingList() {
      return nodeMapping_;
    }
    /**
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     */
    public java.util.List<? extends com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder> 
        getNodeMappingOrBuilderList() {
      return nodeMapping_;
    }
    /**
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     */
    public int getNodeMappingCount() {
      return nodeMapping_.size();
    }
    /**
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     */
    public com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping getNodeMapping(int index) {
      return nodeMapping_.get(index);
    }
    /**
     * <pre>
     * Node mapping for forward requests to. 
     * </pre>
     *
     * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
     */
    public com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder getNodeMappingOrBuilder(
        int index) {
      return nodeMapping_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (daemonPort_ != 0) {
        output.writeInt32(1, daemonPort_);
      }
      for (int i = 0; i < nodeMapping_.size(); i++) {
        output.writeMessage(2, nodeMapping_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (daemonPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, daemonPort_);
      }
      for (int i = 0; i < nodeMapping_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, nodeMapping_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.s13g.winston.master.proto.MasterProtos.Config)) {
        return super.equals(obj);
      }
      com.s13g.winston.master.proto.MasterProtos.Config other = (com.s13g.winston.master.proto.MasterProtos.Config) obj;

      boolean result = true;
      result = result && (getDaemonPort()
          == other.getDaemonPort());
      result = result && getNodeMappingList()
          .equals(other.getNodeMappingList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + DAEMON_PORT_FIELD_NUMBER;
      hash = (53 * hash) + getDaemonPort();
      if (getNodeMappingCount() > 0) {
        hash = (37 * hash) + NODE_MAPPING_FIELD_NUMBER;
        hash = (53 * hash) + getNodeMappingList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.s13g.winston.master.proto.MasterProtos.Config parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.s13g.winston.master.proto.MasterProtos.Config parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.s13g.winston.master.proto.MasterProtos.Config prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Configuration for the master daemon. 
     * </pre>
     *
     * Protobuf type {@code com.s13g.winston.master.proto.Config}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.s13g.winston.master.proto.Config)
        com.s13g.winston.master.proto.MasterProtos.ConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.s13g.winston.master.proto.MasterProtos.Config.class, com.s13g.winston.master.proto.MasterProtos.Config.Builder.class);
      }

      // Construct using com.s13g.winston.master.proto.MasterProtos.Config.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodeMappingFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        daemonPort_ = 0;

        if (nodeMappingBuilder_ == null) {
          nodeMapping_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          nodeMappingBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.s13g.winston.master.proto.MasterProtos.internal_static_com_s13g_winston_master_proto_Config_descriptor;
      }

      public com.s13g.winston.master.proto.MasterProtos.Config getDefaultInstanceForType() {
        return com.s13g.winston.master.proto.MasterProtos.Config.getDefaultInstance();
      }

      public com.s13g.winston.master.proto.MasterProtos.Config build() {
        com.s13g.winston.master.proto.MasterProtos.Config result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.s13g.winston.master.proto.MasterProtos.Config buildPartial() {
        com.s13g.winston.master.proto.MasterProtos.Config result = new com.s13g.winston.master.proto.MasterProtos.Config(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.daemonPort_ = daemonPort_;
        if (nodeMappingBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            nodeMapping_ = java.util.Collections.unmodifiableList(nodeMapping_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.nodeMapping_ = nodeMapping_;
        } else {
          result.nodeMapping_ = nodeMappingBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.s13g.winston.master.proto.MasterProtos.Config) {
          return mergeFrom((com.s13g.winston.master.proto.MasterProtos.Config)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.s13g.winston.master.proto.MasterProtos.Config other) {
        if (other == com.s13g.winston.master.proto.MasterProtos.Config.getDefaultInstance()) return this;
        if (other.getDaemonPort() != 0) {
          setDaemonPort(other.getDaemonPort());
        }
        if (nodeMappingBuilder_ == null) {
          if (!other.nodeMapping_.isEmpty()) {
            if (nodeMapping_.isEmpty()) {
              nodeMapping_ = other.nodeMapping_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureNodeMappingIsMutable();
              nodeMapping_.addAll(other.nodeMapping_);
            }
            onChanged();
          }
        } else {
          if (!other.nodeMapping_.isEmpty()) {
            if (nodeMappingBuilder_.isEmpty()) {
              nodeMappingBuilder_.dispose();
              nodeMappingBuilder_ = null;
              nodeMapping_ = other.nodeMapping_;
              bitField0_ = (bitField0_ & ~0x00000002);
              nodeMappingBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodeMappingFieldBuilder() : null;
            } else {
              nodeMappingBuilder_.addAllMessages(other.nodeMapping_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.s13g.winston.master.proto.MasterProtos.Config parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.s13g.winston.master.proto.MasterProtos.Config) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int daemonPort_ ;
      /**
       * <pre>
       * The port to start the master daemon on. 
       * </pre>
       *
       * <code>optional int32 daemon_port = 1;</code>
       */
      public int getDaemonPort() {
        return daemonPort_;
      }
      /**
       * <pre>
       * The port to start the master daemon on. 
       * </pre>
       *
       * <code>optional int32 daemon_port = 1;</code>
       */
      public Builder setDaemonPort(int value) {
        
        daemonPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The port to start the master daemon on. 
       * </pre>
       *
       * <code>optional int32 daemon_port = 1;</code>
       */
      public Builder clearDaemonPort() {
        
        daemonPort_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping> nodeMapping_ =
        java.util.Collections.emptyList();
      private void ensureNodeMappingIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          nodeMapping_ = new java.util.ArrayList<com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping>(nodeMapping_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder, com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder> nodeMappingBuilder_;

      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public java.util.List<com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping> getNodeMappingList() {
        if (nodeMappingBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodeMapping_);
        } else {
          return nodeMappingBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public int getNodeMappingCount() {
        if (nodeMappingBuilder_ == null) {
          return nodeMapping_.size();
        } else {
          return nodeMappingBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping getNodeMapping(int index) {
        if (nodeMappingBuilder_ == null) {
          return nodeMapping_.get(index);
        } else {
          return nodeMappingBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public Builder setNodeMapping(
          int index, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping value) {
        if (nodeMappingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeMappingIsMutable();
          nodeMapping_.set(index, value);
          onChanged();
        } else {
          nodeMappingBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public Builder setNodeMapping(
          int index, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder builderForValue) {
        if (nodeMappingBuilder_ == null) {
          ensureNodeMappingIsMutable();
          nodeMapping_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodeMappingBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public Builder addNodeMapping(com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping value) {
        if (nodeMappingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeMappingIsMutable();
          nodeMapping_.add(value);
          onChanged();
        } else {
          nodeMappingBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public Builder addNodeMapping(
          int index, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping value) {
        if (nodeMappingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeMappingIsMutable();
          nodeMapping_.add(index, value);
          onChanged();
        } else {
          nodeMappingBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public Builder addNodeMapping(
          com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder builderForValue) {
        if (nodeMappingBuilder_ == null) {
          ensureNodeMappingIsMutable();
          nodeMapping_.add(builderForValue.build());
          onChanged();
        } else {
          nodeMappingBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public Builder addNodeMapping(
          int index, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder builderForValue) {
        if (nodeMappingBuilder_ == null) {
          ensureNodeMappingIsMutable();
          nodeMapping_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodeMappingBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public Builder addAllNodeMapping(
          java.lang.Iterable<? extends com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping> values) {
        if (nodeMappingBuilder_ == null) {
          ensureNodeMappingIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodeMapping_);
          onChanged();
        } else {
          nodeMappingBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public Builder clearNodeMapping() {
        if (nodeMappingBuilder_ == null) {
          nodeMapping_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          nodeMappingBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public Builder removeNodeMapping(int index) {
        if (nodeMappingBuilder_ == null) {
          ensureNodeMappingIsMutable();
          nodeMapping_.remove(index);
          onChanged();
        } else {
          nodeMappingBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder getNodeMappingBuilder(
          int index) {
        return getNodeMappingFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder getNodeMappingOrBuilder(
          int index) {
        if (nodeMappingBuilder_ == null) {
          return nodeMapping_.get(index);  } else {
          return nodeMappingBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public java.util.List<? extends com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder> 
           getNodeMappingOrBuilderList() {
        if (nodeMappingBuilder_ != null) {
          return nodeMappingBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodeMapping_);
        }
      }
      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder addNodeMappingBuilder() {
        return getNodeMappingFieldBuilder().addBuilder(
            com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.getDefaultInstance());
      }
      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder addNodeMappingBuilder(
          int index) {
        return getNodeMappingFieldBuilder().addBuilder(
            index, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.getDefaultInstance());
      }
      /**
       * <pre>
       * Node mapping for forward requests to. 
       * </pre>
       *
       * <code>repeated .com.s13g.winston.master.proto.Config.NodeMapping node_mapping = 2;</code>
       */
      public java.util.List<com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder> 
           getNodeMappingBuilderList() {
        return getNodeMappingFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder, com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder> 
          getNodeMappingFieldBuilder() {
        if (nodeMappingBuilder_ == null) {
          nodeMappingBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping, com.s13g.winston.master.proto.MasterProtos.Config.NodeMapping.Builder, com.s13g.winston.master.proto.MasterProtos.Config.NodeMappingOrBuilder>(
                  nodeMapping_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          nodeMapping_ = null;
        }
        return nodeMappingBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.s13g.winston.master.proto.Config)
    }

    // @@protoc_insertion_point(class_scope:com.s13g.winston.master.proto.Config)
    private static final com.s13g.winston.master.proto.MasterProtos.Config DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.s13g.winston.master.proto.MasterProtos.Config();
    }

    public static com.s13g.winston.master.proto.MasterProtos.Config getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Config>
        PARSER = new com.google.protobuf.AbstractParser<Config>() {
      public Config parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Config(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Config> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Config> getParserForType() {
      return PARSER;
    }

    public com.s13g.winston.master.proto.MasterProtos.Config getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_s13g_winston_master_proto_Config_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_s13g_winston_master_proto_Config_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_s13g_winston_master_proto_Config_NodeMapping_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_s13g_winston_master_proto_Config_NodeMapping_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036etc/protos/master_config.proto\022\035com.s1" +
      "3g.winston.master.proto\"\263\001\n\006Config\022\023\n\013da" +
      "emon_port\030\001 \001(\005\022G\n\014node_mapping\030\002 \003(\01321." +
      "com.s13g.winston.master.proto.Config.Nod" +
      "eMapping\032K\n\013NodeMapping\022\014\n\004name\030\001 \001(\t\022\017\n" +
      "\007address\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\022\017\n\007use_ssl\030" +
      "\004 \001(\010B-\n\035com.s13g.winston.master.protoB\014" +
      "MasterProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_s13g_winston_master_proto_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_s13g_winston_master_proto_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_s13g_winston_master_proto_Config_descriptor,
        new java.lang.String[] { "DaemonPort", "NodeMapping", });
    internal_static_com_s13g_winston_master_proto_Config_NodeMapping_descriptor =
      internal_static_com_s13g_winston_master_proto_Config_descriptor.getNestedTypes().get(0);
    internal_static_com_s13g_winston_master_proto_Config_NodeMapping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_s13g_winston_master_proto_Config_NodeMapping_descriptor,
        new java.lang.String[] { "Name", "Address", "Port", "UseSsl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
